<?php

use Illuminate\Database\Seeder;
use App\Subject;

class SubjectssTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Subject::create(["career_id"=>1,"name"=>"TECNICAS DE COMUNICACION ORAL Y ESCRITA","creditos"=>5]);
        Subject::create(["career_id"=>1,"name"=>"SEMINARIO DE ORIENTACION","creditos"=>1]);
        Subject::create(["career_id"=>1,"name"=>"DIBUJO INDUSTRIAL","creditos"=>5]);
        Subject::create(["career_id"=>1,"name"=>"GEOMETRIA Y TRIGONOMETRIA","creditos"=>0]);
        Subject::create(["career_id"=>1,"name"=>"FISICA A","creditos"=>8]);
        Subject::create(["career_id"=>1,"name"=>"QUIMICA AGROINDUSTRIAL","creditos"=>10]);
        Subject::create(["career_id"=>1,"name"=>"BIOLOGIA PARA INGENIEROS","creditos"=>8]);
        Subject::create(["career_id"=>1,"name"=>"INTRODUCCION A LA INGENIERIA AGROINDUSTRIAL","creditos"=>3]);
        Subject::create(["career_id"=>1,"name"=>"HERRAMIENTAS DE COMPUTO","creditos"=>5]);
        Subject::create(["career_id"=>1,"name"=>"TALLER DE HABILIDADES DIGITALES","creditos"=>3]);
        Subject::create(["career_id"=>1,"name"=>"GEOMETRIA DESCRIPTIVA","creditos"=>5]);
        Subject::create(["career_id"=>1,"name"=>"DISEÑO ASISTIDO POR COMPUTADORA","creditos"=>5]);
        Subject::create(["career_id"=>1,"name"=>"CALCULO A","creditos"=>8]);
        Subject::create(["career_id"=>1,"name"=>"ALGEBRA B","creditos"=>8]);
        Subject::create(["career_id"=>1,"name"=>"BIOQUIMICA","creditos"=>10]);
        Subject::create(["career_id"=>1,"name"=>"TECNOLOGIAS DE LA TRANSFORMACION","creditos"=>3]);
        Subject::create(["career_id"=>1,"name"=>"ADMINISTRACION Y ORGANIZACION","creditos"=>6]);
        Subject::create(["career_id"=>1,"name"=>"INGLES 1","creditos"=>0]);
        Subject::create(["career_id"=>1,"name"=>"ACCIONES AGROECOLOGICAS","creditos"=>8]);
        Subject::create(["career_id"=>1,"name"=>"BALANCE DE MASA Y ENERGIA","creditos"=>8]);
        Subject::create(["career_id"=>1,"name"=>"FISICA B","creditos"=>8]);
        Subject::create(["career_id"=>1,"name"=>"QUIMICA ANALITICA","creditos"=>10]);
        Subject::create(["career_id"=>1,"name"=>"ANATOMIA Y FISIOLOGIA VEGETAL","creditos"=>8]);
        Subject::create(["career_id"=>1,"name"=>"ANATOMIA Y FISIOLOGIA ANIMAL","creditos"=>8]);
        Subject::create(["career_id"=>1,"name"=>"TENDENCIAS SOCIALES","creditos"=>2]);
        Subject::create(["career_id"=>1,"name"=>"INGLES 2","creditos"=>0]);
        Subject::create(["career_id"=>1,"name"=>"CALCULO D","creditos"=>8]);
        Subject::create(["career_id"=>1,"name"=>"TERMODINAMICA","creditos"=>8]);
        Subject::create(["career_id"=>1,"name"=>"MICROBIOLOGIA","creditos"=>10]);
        Subject::create(["career_id"=>1,"name"=>"RELACION SUELO-AGUA PLANTA ATMOSFERA","creditos"=>8]);
        Subject::create(["career_id"=>1,"name"=>"PLANEACION Y EVALUACION DE PROYECTOS","creditos"=>6]);
        Subject::create(["career_id"=>1,"name"=>"INGLES 3","creditos"=>0]);
        Subject::create(["career_id"=>1,"name"=>"ESTADISTICA","creditos"=>10]);
        Subject::create(["career_id"=>1,"name"=>"FISICOQUIMICA","creditos"=>8]);
        Subject::create(["career_id"=>1,"name"=>"PRODUCCION FORESTAL","creditos"=>8]);
        Subject::create(["career_id"=>1,"name"=>"PRODUCCION AGRICOLA","creditos"=>8]);
        Subject::create(["career_id"=>1,"name"=>"PRODUCCION PECUARIA","creditos"=>8]);
        Subject::create(["career_id"=>1,"name"=>"INGENIERIA ECONOMICA Y FINANCIERA","creditos"=>6]);
        Subject::create(["career_id"=>1,"name"=>"LIDERAZGO Y EMPRENDIMIENTO","creditos"=>3]);
        Subject::create(["career_id"=>1,"name"=>"INGLES 4","creditos"=>0]);
        Subject::create(["career_id"=>1,"name"=>"METODOS ESTADISTICOS","creditos"=>8]);
        Subject::create(["career_id"=>1,"name"=>"FISICOQUIMICA DE BIOMOLECULAS","creditos"=>8]);
        Subject::create(["career_id"=>1,"name"=>"FLUJO DE FLUIDOS Y SEPARACIONES MECANICAS","creditos"=>8]);
        Subject::create(["career_id"=>1,"name"=>"FISIOLOGIA POSTRECOLECCION","creditos"=>8]);
        Subject::create(["career_id"=>1,"name"=>"FACTOR HUMANO","creditos"=>6]);
        Subject::create(["career_id"=>1,"name"=>"NEGOCIACION Y COMERCIALIZACION","creditos"=>6]);
        Subject::create(["career_id"=>1,"name"=>"INGLES 5","creditos"=>0]);
        Subject::create(["career_id"=>1,"name"=>"TALLER INTEGRADOR I","creditos"=>5]);
        Subject::create(["career_id"=>1,"name"=>"INGENIERIA DE PROCESOS AGROINDUSTRIALES","creditos"=>10]);
        Subject::create(["career_id"=>1,"name"=>"TRANSFERENCIA DE MASA","creditos"=>8]);
        Subject::create(["career_id"=>1,"name"=>"TRANSFERENCIA DE CALOR","creditos"=>8]);
        Subject::create(["career_id"=>1,"name"=>"BIOTECNOLOGIA","creditos"=>12]);
        Subject::create(["career_id"=>1,"name"=>"ADMINISTRACION DE CALIDAD TOTAL","creditos"=>6]);
        Subject::create(["career_id"=>1,"name"=>"TALLER INTEGRADOR II","creditos"=>5]);
        Subject::create(["career_id"=>1,"name"=>"INGENIERIA DE PLANTA I","creditos"=>10]);
        Subject::create(["career_id"=>1,"name"=>"PROCESOS ALIMENTARIOS AGRICOLAS","creditos"=>11]);
        Subject::create(["career_id"=>1,"name"=>"PROCESOS NO ALIMENTARIOS I","creditos"=>8]);
        Subject::create(["career_id"=>1,"name"=>"DESARROLLO EMPRESARIAL","creditos"=>6]);
        Subject::create(["career_id"=>1,"name"=>"TALLER INTEGRADOR III","creditos"=>5]);
        Subject::create(["career_id"=>1,"name"=>"INGENIERIA DE PLANTA II","creditos"=>10]);
        Subject::create(["career_id"=>1,"name"=>"PROCESOS FORESTALES","creditos"=>8]);
        Subject::create(["career_id"=>1,"name"=>"PROCESOS ALIMENTARIOS PECUARIOS","creditos"=>11]);
        Subject::create(["career_id"=>1,"name"=>"PROCESOS NO ALIMENTARIOS II","creditos"=>8]);
        Subject::create(["career_id"=>1,"name"=>"PRACTICAS PROFESIONALES I","creditos"=>15]);
        Subject::create(["career_id"=>2,"name"=>"SEMINARIO DE ORIENTACION ING. AMBIENTAL","creditos"=>0]);
        Subject::create(["career_id"=>2,"name"=>"BIODIVERSIDAD Y EVOLUCION","creditos"=>9]);
        Subject::create(["career_id"=>2,"name"=>"PROBLEMATICA AMBIENTAL","creditos"=>9]);
        Subject::create(["career_id"=>2,"name"=>"ALGEBRA A","creditos"=>8]);
        Subject::create(["career_id"=>2,"name"=>"QUIMICA A","creditos"=>8]);
        Subject::create(["career_id"=>2,"name"=>"CALCULO A","creditos"=>8]);
        Subject::create(["career_id"=>2,"name"=>"GEOMETRIA Y TRIGONOMETRIA","creditos"=>0]);
        Subject::create(["career_id"=>2,"name"=>"METODOLOGIA DE LA INVESTIGACION","creditos"=>4]);
        Subject::create(["career_id"=>2,"name"=>"ECOLOGIA GENERAL","creditos"=>9]);
        Subject::create(["career_id"=>2,"name"=>"ALGEBRA B","creditos"=>8]);
        Subject::create(["career_id"=>2,"name"=>"QUIMICA ORGANICA AMBIENTAL","creditos"=>6]);
        Subject::create(["career_id"=>2,"name"=>"CALCULO B","creditos"=>8]);
        Subject::create(["career_id"=>2,"name"=>"FISICA A","creditos"=>8]);
        Subject::create(["career_id"=>2,"name"=>"TECNICAS DE COMUNICACION ORAL Y ESCRITA","creditos"=>5]);
        Subject::create(["career_id"=>2,"name"=>"INGLES 1","creditos"=>0]);
        Subject::create(["career_id"=>2,"name"=>"GEOLOGIA BASICA I","creditos"=>10]);
        Subject::create(["career_id"=>2,"name"=>"METEOROLOGIA / CLIMATOLOGIA","creditos"=>7]);
        Subject::create(["career_id"=>2,"name"=>"DESARROLLO SOSTENIBLE","creditos"=>4]);
        Subject::create(["career_id"=>2,"name"=>"COMPUTACION APLICADA A LA INGENIERIA AMBIENTAL I","creditos"=>5]);
        Subject::create(["career_id"=>2,"name"=>"FISICA C","creditos"=>6]);
        Subject::create(["career_id"=>2,"name"=>"TERMODINAMICA I","creditos"=>8]);
        Subject::create(["career_id"=>2,"name"=>"CALCULO D","creditos"=>8]);
        Subject::create(["career_id"=>2,"name"=>"INGLES 2","creditos"=>0]);
        Subject::create(["career_id"=>2,"name"=>"PROBABILIDAD Y ESTADISTICA","creditos"=>8]);
        Subject::create(["career_id"=>2,"name"=>"EDAFOLOGIA AMBIENTAL","creditos"=>7]);
        Subject::create(["career_id"=>2,"name"=>"COMPUTACION APLICADA A LA INGENIERIA AMBIENTAL II","creditos"=>7]);
        Subject::create(["career_id"=>2,"name"=>"QUIMICA DE SOLUCIONES","creditos"=>6]);
        Subject::create(["career_id"=>2,"name"=>"TERMODINAMICA II","creditos"=>8]);
        Subject::create(["career_id"=>2,"name"=>"BALANCES DE MATERIA Y ENERGIA","creditos"=>10]);
        Subject::create(["career_id"=>2,"name"=>"TENDENCIAS SOCIALES","creditos"=>2]);
        Subject::create(["career_id"=>2,"name"=>"INGLES 3","creditos"=>0]);
        Subject::create(["career_id"=>2,"name"=>"INFERENCIA ESTADISTICA","creditos"=>8]);
        Subject::create(["career_id"=>2,"name"=>"ADMINISTRACION Y COACHING EMPRESARIAL","creditos"=>8]);
        Subject::create(["career_id"=>2,"name"=>"GESTION AMBIENTAL","creditos"=>6]);
        Subject::create(["career_id"=>2,"name"=>"HIDRAULICA AMBIENTAL","creditos"=>8]);
        Subject::create(["career_id"=>2,"name"=>"QUIMICA AMBIENTAL","creditos"=>6]);
        Subject::create(["career_id"=>2,"name"=>"QUIMICA ANALITICA","creditos"=>6]);
        Subject::create(["career_id"=>2,"name"=>"FENOMENOS DE TRANSPORTE","creditos"=>6]);
        Subject::create(["career_id"=>2,"name"=>"GESTION Y DESARROLLO SOCIAL","creditos"=>2]);
        Subject::create(["career_id"=>2,"name"=>"INGLES 4","creditos"=>0]);
        Subject::create(["career_id"=>2,"name"=>"INGENIERIA ECONOMICA","creditos"=>8]);
        Subject::create(["career_id"=>2,"name"=>"INSTRUMENTACION Y CONTROL DE PROCESOS","creditos"=>7]);
        Subject::create(["career_id"=>2,"name"=>"HIDROLOGIA","creditos"=>6]);
        Subject::create(["career_id"=>2,"name"=>"MANEJO DE RECURSOS NATURALES","creditos"=>9]);
        Subject::create(["career_id"=>2,"name"=>"LABORATORIO DE CIENCIAS AMBIENTALES I","creditos"=>4]);
        Subject::create(["career_id"=>2,"name"=>"MICROBIOLOGIA AMBIENTAL","creditos"=>7]);
        Subject::create(["career_id"=>2,"name"=>"CINETICA EN INGENIERIA AMBIENTAL","creditos"=>6]);
        Subject::create(["career_id"=>2,"name"=>"LIDERAZGO Y EMPRENDIMIENTO","creditos"=>3]);
        Subject::create(["career_id"=>2,"name"=>"INGLES 5","creditos"=>0]);
        Subject::create(["career_id"=>2,"name"=>"FORMULACION Y GESTION DE PROYECTOS","creditos"=>7]);
        Subject::create(["career_id"=>2,"name"=>"SEGURIDAD E HIGIENE EN LA INDUSTRIA","creditos"=>10]);
        Subject::create(["career_id"=>2,"name"=>"AREAS NATURALES PROTEGIDAS Y PLANES DE MANEJO","creditos"=>5]);
        Subject::create(["career_id"=>2,"name"=>"LABORATORIO DE CIENCIAS AMBIENTALES II","creditos"=>4]);
        Subject::create(["career_id"=>2,"name"=>"PREVENCION Y CONTROL DE LA CONTAMINACION DEL AIRE","creditos"=>7]);
        Subject::create(["career_id"=>2,"name"=>"BIOTECNOLOGIA AMBIENTAL","creditos"=>6]);
        Subject::create(["career_id"=>2,"name"=>"ARTE- CULTURA Y HUMANIDADES I","creditos"=>2]);
        Subject::create(["career_id"=>2,"name"=>"VALIDACION DE LA LENGUA EXTRANJERA","creditos"=>0]);
        Subject::create(["career_id"=>2,"name"=>"ECONOMIA AMBIENTAL","creditos"=>8]);
        Subject::create(["career_id"=>2,"name"=>"EVALUACION DE IMPACTO AMBIENTAL","creditos"=>7]);
        Subject::create(["career_id"=>2,"name"=>"EVALUACION DE RIESGO AMBIENTAL","creditos"=>5]);
        Subject::create(["career_id"=>2,"name"=>"ARTE- CULTURA Y HUMANIDADES II","creditos"=>2]);
        Subject::create(["career_id"=>2,"name"=>"PREVENCION Y CONTROL DE LA CONTAMINACION DEL AGUA","creditos"=>7]);
        Subject::create(["career_id"=>2,"name"=>"GESTION Y CONTROL DE LOS RESIDUOS","creditos"=>7]);
        Subject::create(["career_id"=>2,"name"=>"DESARROLLO DE PROYECTOS","creditos"=>15]);
        Subject::create(["career_id"=>2,"name"=>"ACTIVIDADES ARTISTICAS- DEPORTIVAS O DE DIVULGACION","creditos"=>2]);
        Subject::create(["career_id"=>3,"name"=>"ALGEBRA A","creditos"=>8]);
        Subject::create(["career_id"=>3,"name"=>"HERRAMIENTAS DE COMPUTO I","creditos"=>4]);
        Subject::create(["career_id"=>3,"name"=>"CALCULO A","creditos"=>8]);
        Subject::create(["career_id"=>3,"name"=>"GEOMETRIA Y TRIGONOMETRIA","creditos"=>0]);
        Subject::create(["career_id"=>3,"name"=>"FISICA A","creditos"=>8]);
        Subject::create(["career_id"=>3,"name"=>"GEOLOGIA APLICADA A LA ING. CIVIL","creditos"=>8]);
        Subject::create(["career_id"=>3,"name"=>"GEOMETRIA DESCRIPTIVA","creditos"=>5]);
        Subject::create(["career_id"=>3,"name"=>"SEMINARIO Y VISITAS DE OBRA I","creditos"=>1]);
        Subject::create(["career_id"=>3,"name"=>"METODOLOGIA DE LA INVESTIGACION","creditos"=>4]);
        Subject::create(["career_id"=>3,"name"=>"SEMINARIO DE ORIENTACION ING. CIVIL","creditos"=>0]);
        Subject::create(["career_id"=>3,"name"=>"ALGEBRA B","creditos"=>8]);
        Subject::create(["career_id"=>3,"name"=>"HERRAMIENTAS DE COMPUTO II","creditos"=>3]);
        Subject::create(["career_id"=>3,"name"=>"CALCULO B","creditos"=>8]);
        Subject::create(["career_id"=>3,"name"=>"ESTATICA","creditos"=>10]);
        Subject::create(["career_id"=>3,"name"=>"MATERIALES DE CONSTRUCCION","creditos"=>7]);
        Subject::create(["career_id"=>3,"name"=>"DIBUJO CIVIL Y ARQUITECTONICO","creditos"=>5]);
        Subject::create(["career_id"=>3,"name"=>"SEMINARIO Y VISITAS DE OBRA II","creditos"=>1]);
        Subject::create(["career_id"=>3,"name"=>"TECNICAS DE COMUNICACION ORAL Y ESCRITA","creditos"=>5]);
        Subject::create(["career_id"=>3,"name"=>"INGLES 1","creditos"=>0]);
        Subject::create(["career_id"=>3,"name"=>"ESTADISTICA APLICADA","creditos"=>8]);
        Subject::create(["career_id"=>3,"name"=>"ANALISIS NUMERICO","creditos"=>6]);
        Subject::create(["career_id"=>3,"name"=>"CALCULO D","creditos"=>8]);
        Subject::create(["career_id"=>3,"name"=>"ANALISIS DE ESTRUCTURAS ISOSTATICAS","creditos"=>10]);
        Subject::create(["career_id"=>3,"name"=>"TOPOGRAFIA","creditos"=>10]);
        Subject::create(["career_id"=>3,"name"=>"FISICA C","creditos"=>6]);
        Subject::create(["career_id"=>3,"name"=>"SEMINARIO Y VISITAS DE OBRA III","creditos"=>1]);
        Subject::create(["career_id"=>3,"name"=>"LIDERAZGO Y EMPRENDIMIENTO","creditos"=>3]);
        Subject::create(["career_id"=>3,"name"=>"INGLES 2","creditos"=>0]);
        Subject::create(["career_id"=>3,"name"=>"INGENIERIA DE SISTEMAS","creditos"=>8]);
        Subject::create(["career_id"=>3,"name"=>"HERRAMIENTAS DE COMPUTO III","creditos"=>6]);
        Subject::create(["career_id"=>3,"name"=>"CINEMATICA","creditos"=>8]);
        Subject::create(["career_id"=>3,"name"=>"MECANICA DE MATERIALES","creditos"=>10]);
        Subject::create(["career_id"=>3,"name"=>"CONSTRUCCION I","creditos"=>10]);
        Subject::create(["career_id"=>3,"name"=>"SISTEMAS ELECTROMECANICOS","creditos"=>6]);
        Subject::create(["career_id"=>3,"name"=>"ARTE- CULTURA Y HUMANIDADES I","creditos"=>2]);
        Subject::create(["career_id"=>3,"name"=>"INGLES 3","creditos"=>0]);
        Subject::create(["career_id"=>3,"name"=>"TEORIA DE LA PLANEACION","creditos"=>6]);
        Subject::create(["career_id"=>3,"name"=>"HIDRAULICA I","creditos"=>12]);
        Subject::create(["career_id"=>3,"name"=>"CINETICA","creditos"=>8]);
        Subject::create(["career_id"=>3,"name"=>"ANALISIS DE ESTRUCTURAS HIPERESTATICAS I","creditos"=>10]);
        Subject::create(["career_id"=>3,"name"=>"GEOTECNIA I","creditos"=>12]);
        Subject::create(["career_id"=>3,"name"=>"ARTE- CULTURA Y HUMANIDADES II","creditos"=>2]);
        Subject::create(["career_id"=>3,"name"=>"INGLES 4","creditos"=>0]);
        Subject::create(["career_id"=>3,"name"=>"QUIMICA DEL AGUA","creditos"=>8]);
        Subject::create(["career_id"=>3,"name"=>"HIDRAULICA II","creditos"=>11]);
        Subject::create(["career_id"=>3,"name"=>"ESTRUCTURAS DE CONCRETO","creditos"=>10]);
        Subject::create(["career_id"=>3,"name"=>"ANALISIS DE ESTRUCTURAS HIPERESTATICAS II","creditos"=>10]);
        Subject::create(["career_id"=>3,"name"=>"CONSTRUCCION II","creditos"=>10]);
        Subject::create(["career_id"=>3,"name"=>"ACTIVIDADES ARTISTICAS- DEPORTIVAS O DE DIVULGACION","creditos"=>2]);
        Subject::create(["career_id"=>3,"name"=>"INGLES 5","creditos"=>0]);
        Subject::create(["career_id"=>3,"name"=>"ADMINISTRACION- ECONOMIA Y LEGISLACION EN LA CONSTRUCCION","creditos"=>8]);
        Subject::create(["career_id"=>3,"name"=>"INGENIERIA SANITARIA","creditos"=>10]);
        Subject::create(["career_id"=>3,"name"=>"HIDROLOGIA","creditos"=>8]);
        Subject::create(["career_id"=>3,"name"=>"ESTRUCTURAS DE ACERO","creditos"=>10]);
        Subject::create(["career_id"=>3,"name"=>"SIMULACION DE SISTEMAS ESTRUCTURALES","creditos"=>6]);
        Subject::create(["career_id"=>3,"name"=>"GEOTECNIA II","creditos"=>10]);
        Subject::create(["career_id"=>3,"name"=>"TALLER DE PROYECTOS I","creditos"=>6]);
        Subject::create(["career_id"=>3,"name"=>"INSTALACIONES EN EDIFICIOS","creditos"=>8]);
        Subject::create(["career_id"=>3,"name"=>"OBRAS HIDRAULICAS","creditos"=>10]);
        Subject::create(["career_id"=>3,"name"=>"GEOHIDROLOGIA","creditos"=>8]);
        Subject::create(["career_id"=>3,"name"=>"CIMENTACIONES","creditos"=>6]);
        Subject::create(["career_id"=>3,"name"=>"CONSTRUCCION III","creditos"=>10]);
        Subject::create(["career_id"=>3,"name"=>"TALLER DE PROYECTOS II","creditos"=>6]);
        Subject::create(["career_id"=>3,"name"=>"URBANISMO","creditos"=>6]);
        Subject::create(["career_id"=>3,"name"=>"PUENTES","creditos"=>8]);
        Subject::create(["career_id"=>3,"name"=>"INGENIERIA SISMICA","creditos"=>6]);
        Subject::create(["career_id"=>3,"name"=>"VIAS TERRESTRES","creditos"=>10]);
        Subject::create(["career_id"=>3,"name"=>"CONSTRUCCION IV","creditos"=>6]);
        Subject::create(["career_id"=>3,"name"=>"LICITACION DE OBRAS","creditos"=>6]);
        Subject::create(["career_id"=>3,"name"=>"TALLER DE PROYECTOS III","creditos"=>10]);
        Subject::create(["career_id"=>3,"name"=>"INGENIERIA SUSTENTABLE","creditos"=>6]);
        Subject::create(["career_id"=>3,"name"=>"INGENIERIA VIAL","creditos"=>8]);
        Subject::create(["career_id"=>3,"name"=>"PRACTICAS PROFESIONALES I","creditos"=>15]);
        Subject::create(["career_id"=>3,"name"=>"INGENIERIA DE COSTOS- CONTABILIDAD Y ESTADOS FINANCIEROS","creditos"=>6]);
        Subject::create(["career_id"=>3,"name"=>"TALLER DE PROYECTOS IV","creditos"=>10]);
        Subject::create(["career_id"=>3,"name"=>"SEMINARIO DE EGRESO","creditos"=>0]);
        Subject::create(["career_id"=>4,"name"=>"QUIMICA A","creditos"=>8]);
        Subject::create(["career_id"=>4,"name"=>"MATEMATICAS DISCRETAS I","creditos"=>8]);
        Subject::create(["career_id"=>4,"name"=>"PENSAMIENTO ALGORITMICO","creditos"=>8]);
        Subject::create(["career_id"=>4,"name"=>"TEMAS SELECTOS DE MATEMATICAS","creditos"=>8]);
        Subject::create(["career_id"=>4,"name"=>"HERRAMIENTAS DE SOFTWARE","creditos"=>8]);
        Subject::create(["career_id"=>4,"name"=>"SEMINARIO DE ORIENTACION EN COMPUTACION","creditos"=>2]);
        Subject::create(["career_id"=>4,"name"=>"METODOLOGIA DE LA INVESTIGACION","creditos"=>4]);
        Subject::create(["career_id"=>4,"name"=>"CALCULO A","creditos"=>8]);
        Subject::create(["career_id"=>4,"name"=>"MATEMATICAS DISCRETAS II","creditos"=>8]);
        Subject::create(["career_id"=>4,"name"=>"ESTRUCTURAS DE DATOS I","creditos"=>8]);
        Subject::create(["career_id"=>4,"name"=>"ALGEBRA B","creditos"=>8]);
        Subject::create(["career_id"=>4,"name"=>"FUNDAMENTOS DE CURCUITOS ELECTRICOS","creditos"=>10]);
        Subject::create(["career_id"=>4,"name"=>"ARTE- CULTURA Y HUMANIDADES I","creditos"=>2]);
        Subject::create(["career_id"=>4,"name"=>"INGLES 1","creditos"=>5]);
        Subject::create(["career_id"=>4,"name"=>"CALCULO B","creditos"=>8]);
        Subject::create(["career_id"=>4,"name"=>"INGENIERIA DE SOFTWARE","creditos"=>8]);
        Subject::create(["career_id"=>4,"name"=>"ESTRUCTURAS DE DATOS II","creditos"=>8]);
        Subject::create(["career_id"=>4,"name"=>"LENGUAJES DE PROGRAMACION","creditos"=>8]);
        Subject::create(["career_id"=>4,"name"=>"DISPOSITIVOS SEMICONDUCTORES","creditos"=>10]);
        Subject::create(["career_id"=>4,"name"=>"FUNDAMENTOS DE DISEÑO DIGITAL","creditos"=>8]);
        Subject::create(["career_id"=>4,"name"=>"CALCULO D","creditos"=>8]);
        Subject::create(["career_id"=>4,"name"=>"FISICA A","creditos"=>8]);
        Subject::create(["career_id"=>4,"name"=>"TECNOLOGIA ORIENTADA A OBJETOS","creditos"=>8]);
        Subject::create(["career_id"=>4,"name"=>"ALGORITMOS Y COMPLEJIDAD","creditos"=>8]);
        Subject::create(["career_id"=>4,"name"=>"DISEÑO DIGITAL","creditos"=>10]);
        Subject::create(["career_id"=>4,"name"=>"TENDENCIAS SOCIALES","creditos"=>2]);
        Subject::create(["career_id"=>4,"name"=>"INGLES 2","creditos"=>5]);
        Subject::create(["career_id"=>4,"name"=>"ANALISIS NUMERICO","creditos"=>8]);
        Subject::create(["career_id"=>4,"name"=>"INTERFACES GRAFICAS CON APLICACIONES","creditos"=>8]);
        Subject::create(["career_id"=>4,"name"=>"SISTEMAS OPERATIVOS","creditos"=>8]);
        Subject::create(["career_id"=>4,"name"=>"DISEÑO DE MICROCOMPUTADORAS","creditos"=>8]);
        Subject::create(["career_id"=>4,"name"=>"GESTION Y DESARROLLO SOCIAL","creditos"=>2]);
        Subject::create(["career_id"=>4,"name"=>"INGLES 3","creditos"=>5]);
        Subject::create(["career_id"=>4,"name"=>"INGENIERIA DE SOFTWARE B","creditos"=>8]);
        Subject::create(["career_id"=>4,"name"=>"GRAFOS","creditos"=>10]);
        Subject::create(["career_id"=>4,"name"=>"PROBABILIDAD Y ESTADISTICA","creditos"=>8]);
        Subject::create(["career_id"=>4,"name"=>"ADMINISTRACION","creditos"=>8]);
        Subject::create(["career_id"=>4,"name"=>"MICROCONTROLADORES","creditos"=>10]);
        Subject::create(["career_id"=>4,"name"=>"TECNICAS DE COMUNICACION ORAL Y ESCRITA","creditos"=>5]);
        Subject::create(["career_id"=>4,"name"=>"INGLES 4","creditos"=>5]);
        Subject::create(["career_id"=>4,"name"=>"ADMINISTRACION DE PROYECTOS I","creditos"=>8]);
        Subject::create(["career_id"=>4,"name"=>"GRAFICACION POR COMPUTADORA","creditos"=>8]);
        Subject::create(["career_id"=>4,"name"=>"COMPILADORES E INTERPRETES A","creditos"=>10]);
        Subject::create(["career_id"=>4,"name"=>"SISTEMAS OPERATIVOS B","creditos"=>10]);
        Subject::create(["career_id"=>4,"name"=>"ESTRUCTURAS DE ARCHIVOS","creditos"=>8]);
        Subject::create(["career_id"=>4,"name"=>"ROBOTICA","creditos"=>8]);
        Subject::create(["career_id"=>4,"name"=>"INGLES 5","creditos"=>5]);
        Subject::create(["career_id"=>4,"name"=>"ADMINISTRACION DE SISTEMAS","creditos"=>8]);
        Subject::create(["career_id"=>4,"name"=>"GRAFICACION POR COMPUTADORA B","creditos"=>10]);
        Subject::create(["career_id"=>4,"name"=>"PROGRAMACION DE SISTEMAS","creditos"=>12]);
        Subject::create(["career_id"=>4,"name"=>"BASES DE DATOS A","creditos"=>10]);
        Subject::create(["career_id"=>4,"name"=>"ADMINISTRACION INFORMATICA A","creditos"=>8]);
        Subject::create(["career_id"=>4,"name"=>"ARTE- CULTURA Y HUMANIDADES II","creditos"=>2]);
        Subject::create(["career_id"=>4,"name"=>"FUNDAMENTOS DE DESARROLLO WEB","creditos"=>8]);
        Subject::create(["career_id"=>4,"name"=>"FUNDAMENTOS DE INTELIGENCIA ARTIFICIAL","creditos"=>8]);
        Subject::create(["career_id"=>4,"name"=>"COMPUTACION UBICUA","creditos"=>8]);
        Subject::create(["career_id"=>4,"name"=>"ADMINISTRACION DE BASES DE DATOS","creditos"=>8]);
        Subject::create(["career_id"=>4,"name"=>"PROYECTO INTEGRADOR","creditos"=>10]);
        Subject::create(["career_id"=>4,"name"=>"REDES A","creditos"=>12]);
        Subject::create(["career_id"=>4,"name"=>"INTERFACES DE COMUNICACIONES","creditos"=>8]);
        Subject::create(["career_id"=>4,"name"=>"LIDERAZGO Y EMPRENDIMIENTO","creditos"=>3]);
        Subject::create(["career_id"=>4,"name"=>"PRACTICAS PROFESIONALES I","creditos"=>15]);
        Subject::create(["career_id"=>4,"name"=>"SUPERCOMPUTO","creditos"=>8]);
        Subject::create(["career_id"=>4,"name"=>"VISION COMPUTACIONAL","creditos"=>8]);
        Subject::create(["career_id"=>4,"name"=>"TECNOLOGIA INFORMATICA","creditos"=>6]);
        Subject::create(["career_id"=>4,"name"=>"TELEMATICA A","creditos"=>8]);
        Subject::create(["career_id"=>4,"name"=>"REDES B","creditos"=>10]);
        Subject::create(["career_id"=>4,"name"=>"SEMINARIO I.C.","creditos"=>1]);
        Subject::create(["career_id"=>4,"name"=>"ACTIVIDADES ARTISTICAS- DEPORTIVAS O DE DIVULGACION","creditos"=>2]);
        Subject::create(["career_id"=>4,"name"=>"SEMINARIO DE EGRESO","creditos"=>0]);
        Subject::create(["career_id"=>5,"name"=>"DISEÑO ASISTIDO POR COMPUTADORA","creditos"=>3]);
        Subject::create(["career_id"=>5,"name"=>"QUIMICA A","creditos"=>8]);
        Subject::create(["career_id"=>5,"name"=>"ALGEBRA A","creditos"=>8]);
        Subject::create(["career_id"=>5,"name"=>"GEOMETRIA DESCRIPTIVA","creditos"=>5]);
        Subject::create(["career_id"=>5,"name"=>"CALCULO A","creditos"=>8]);
        Subject::create(["career_id"=>5,"name"=>"FISICA A","creditos"=>8]);
        Subject::create(["career_id"=>5,"name"=>"GEOMETRIA Y TRIGONOMETRIA","creditos"=>0]);
        Subject::create(["career_id"=>5,"name"=>"METODOLOGIA DE LA INVESTIGACION","creditos"=>4]);
        Subject::create(["career_id"=>5,"name"=>"SEMINARIO DE ORIENTACION IEA","creditos"=>1]);
        Subject::create(["career_id"=>5,"name"=>"MATERIALES PARA INGENIERIA","creditos"=>9]);
        Subject::create(["career_id"=>5,"name"=>"ELECTRICIDAD Y MAGNETISMO A","creditos"=>9]);
        Subject::create(["career_id"=>5,"name"=>"CALCULO C","creditos"=>6]);
        Subject::create(["career_id"=>5,"name"=>"CALCULO B","creditos"=>8]);
        Subject::create(["career_id"=>5,"name"=>"ESTATICA","creditos"=>8]);
        Subject::create(["career_id"=>5,"name"=>"TECNICAS DE COMUNICACION ORAL Y ESCRITA","creditos"=>5]);
        Subject::create(["career_id"=>5,"name"=>"INGLES 1","creditos"=>0]);
        Subject::create(["career_id"=>5,"name"=>"ALGEBRA B","creditos"=>8]);
        Subject::create(["career_id"=>5,"name"=>"ELECTRICIDAD Y MAGNETISMO B","creditos"=>9]);
        Subject::create(["career_id"=>5,"name"=>"CALCULO D","creditos"=>8]);
        Subject::create(["career_id"=>5,"name"=>"SISTEMAS DE ALUMBRADO","creditos"=>6]);
        Subject::create(["career_id"=>5,"name"=>"MECANICA DE MATERIALES I","creditos"=>11]);
        Subject::create(["career_id"=>5,"name"=>"INGLES 2","creditos"=>0]);
        Subject::create(["career_id"=>5,"name"=>"MODELADO Y SIMULACION","creditos"=>8]);
        Subject::create(["career_id"=>5,"name"=>"INTRODUCCIÓN A LA PROGRAMACIÓN","creditos"=>8]);
        Subject::create(["career_id"=>5,"name"=>"CIRCUITOS ELECTRICOS A","creditos"=>12]);
        Subject::create(["career_id"=>5,"name"=>"PROBABILIDAD E INFERENCIA ESTADISTICA","creditos"=>10]);
        Subject::create(["career_id"=>5,"name"=>"DINAMICA","creditos"=>8]);
        Subject::create(["career_id"=>5,"name"=>"INGLES 3","creditos"=>0]);
        Subject::create(["career_id"=>5,"name"=>"INSTRUMENTACION INDUSTRIAL","creditos"=>7]);
        Subject::create(["career_id"=>5,"name"=>"DISEÑO DE SISTEMAS DIGITALES","creditos"=>7]);
        Subject::create(["career_id"=>5,"name"=>"ELECTRONICA I","creditos"=>12]);
        Subject::create(["career_id"=>5,"name"=>"CIRCUITOS ELECTRICOS B","creditos"=>10]);
        Subject::create(["career_id"=>5,"name"=>"TERMODINAMICA","creditos"=>11]);
        Subject::create(["career_id"=>5,"name"=>"INGLES 4","creditos"=>0]);
        Subject::create(["career_id"=>5,"name"=>"INGENIERIA DE CONTROL I","creditos"=>8]);
        Subject::create(["career_id"=>5,"name"=>"ELECTRONICA II","creditos"=>8]);
        Subject::create(["career_id"=>5,"name"=>"MAQUINAS ELECTRICAS I","creditos"=>12]);
        Subject::create(["career_id"=>5,"name"=>"DIAGRAMAS ELECTRICOS","creditos"=>3]);
        Subject::create(["career_id"=>5,"name"=>"TECNOLOGIA DE PLANTAS GENERADORAS","creditos"=>8]);
        Subject::create(["career_id"=>5,"name"=>"PRINCIPIOS DE ADMINISTRACION","creditos"=>6]);
        Subject::create(["career_id"=>5,"name"=>"INGLES 5","creditos"=>0]);
        Subject::create(["career_id"=>5,"name"=>"ELECTRONEUMATICA","creditos"=>8]);
        Subject::create(["career_id"=>5,"name"=>"MICROCONTROLADORES","creditos"=>7]);
        Subject::create(["career_id"=>5,"name"=>"ELECTRONICA DE POTENCIA I","creditos"=>8]);
        Subject::create(["career_id"=>5,"name"=>"ANALISIS NUMERICO","creditos"=>6]);
        Subject::create(["career_id"=>5,"name"=>"MAQUINAS ELECTRICAS II","creditos"=>12]);
        Subject::create(["career_id"=>5,"name"=>"INGENIERIA Y GESTION AMBIENTAL","creditos"=>3]);
        Subject::create(["career_id"=>5,"name"=>"LIDERAZGO Y EMPRENDIMIENTO","creditos"=>3]);
        Subject::create(["career_id"=>5,"name"=>"VALIDACION DE LA LENGUA EXTRANJERA","creditos"=>0]);
        Subject::create(["career_id"=>5,"name"=>"CONTROL LOGICO PROGRAMABLE","creditos"=>8]);
        Subject::create(["career_id"=>5,"name"=>"ELECTRONICA DE POTENCIA II","creditos"=>8]);
        Subject::create(["career_id"=>5,"name"=>"ADMINISTRACION DE PROYECTOS","creditos"=>6]);
        Subject::create(["career_id"=>5,"name"=>"SISTEMAS ELECTRICOS DE POTENCIA I","creditos"=>9]);
        Subject::create(["career_id"=>5,"name"=>"INSTALACIONES ELECTRICAS A","creditos"=>10]);
        Subject::create(["career_id"=>5,"name"=>"CONTROL DE CALIDAD","creditos"=>6]);
        Subject::create(["career_id"=>5,"name"=>"INGENIERIA DE CONTROL II","creditos"=>8]);
        Subject::create(["career_id"=>5,"name"=>"PROYECTO INTEGRADOR IEA","creditos"=>10]);
        Subject::create(["career_id"=>5,"name"=>"SISTEMAS ELECTRICOS DE POTENCIA II","creditos"=>8]);
        Subject::create(["career_id"=>5,"name"=>"SUBESTACIONES ELECTRICAS A","creditos"=>10]);
        Subject::create(["career_id"=>5,"name"=>"ADMINISTRACION DE PERSONAL","creditos"=>6]);
        Subject::create(["career_id"=>5,"name"=>"SEMINARIO","creditos"=>2]);
        Subject::create(["career_id"=>5,"name"=>"PRACTICAS PROFESIONALES I","creditos"=>15]);
        Subject::create(["career_id"=>5,"name"=>"SEMINARIO DE EGRESO","creditos"=>0]);
        Subject::create(["career_id"=>6,"name"=>"TECNICAS DE COMUNICACION ORAL Y ESCRITA","creditos"=>5]);
        Subject::create(["career_id"=>6,"name"=>"GEOMETRIA Y TRIGONOMETRIA","creditos"=>0]);
        Subject::create(["career_id"=>6,"name"=>"TECNOLOGIAS PARA EL MANEJO DE DATOS ESPACIALES","creditos"=>9]);
        Subject::create(["career_id"=>6,"name"=>"INTRODUCCION A LAS CIENCIAS GEOESPACIALES","creditos"=>10]);
        Subject::create(["career_id"=>6,"name"=>"GEOMETRIA DESCRIPTIVA","creditos"=>5]);
        Subject::create(["career_id"=>6,"name"=>"ALGEBRA A","creditos"=>8]);
        Subject::create(["career_id"=>6,"name"=>"METEOROLOGIA Y CLIMATOLOGIA","creditos"=>8]);
        Subject::create(["career_id"=>6,"name"=>"BASES DE DATOS ORIENTADAS A OBJETOS","creditos"=>8]);
        Subject::create(["career_id"=>6,"name"=>"PROGRAMACION ORIENTADA A OBJETOS","creditos"=>8]);
        Subject::create(["career_id"=>6,"name"=>"FISICA A","creditos"=>8]);
        Subject::create(["career_id"=>6,"name"=>"DIBUJO PARA INGENIEROS","creditos"=>5]);
        Subject::create(["career_id"=>6,"name"=>"ESTADISTICA","creditos"=>10]);
        Subject::create(["career_id"=>6,"name"=>"ALGEBRA B","creditos"=>8]);
        Subject::create(["career_id"=>6,"name"=>"INGLES 1","creditos"=>0]);
        Subject::create(["career_id"=>6,"name"=>"CALCULO A","creditos"=>8]);
        Subject::create(["career_id"=>6,"name"=>"FISICA Y ALTIMETRIA DE SATELITES","creditos"=>8]);
        Subject::create(["career_id"=>6,"name"=>"TOPOGRAFIA PLANIMETRICA Y ALTIMETRICA","creditos"=>12]);
        Subject::create(["career_id"=>6,"name"=>"FUNDAMENTOS DE SISTEMAS DE INFORMACION GEOGRAFICOS","creditos"=>8]);
        Subject::create(["career_id"=>6,"name"=>"FOTOGRAMETRIA DIGITAL","creditos"=>8]);
        Subject::create(["career_id"=>6,"name"=>"PROYECCIONES CARTOGRAFICAS","creditos"=>8]);
        Subject::create(["career_id"=>6,"name"=>"METODOLOGIA DE LA INVESTIGACION","creditos"=>4]);
        Subject::create(["career_id"=>6,"name"=>"INGLES 2","creditos"=>0]);
        Subject::create(["career_id"=>6,"name"=>"CALCULO B","creditos"=>8]);
        Subject::create(["career_id"=>6,"name"=>"LENGUAJE DE PROGRAMACION I","creditos"=>8]);
        Subject::create(["career_id"=>6,"name"=>"ASTRONOMIA PARA EL POSICIONAMIENTO","creditos"=>5]);
        Subject::create(["career_id"=>6,"name"=>"TOPOGRAFIA SUBTERRANEA","creditos"=>8]);
        Subject::create(["career_id"=>6,"name"=>"FUNDAMENTOS DE TELEDETECCION","creditos"=>8]);
        Subject::create(["career_id"=>6,"name"=>"QUIMICA A","creditos"=>8]);
        Subject::create(["career_id"=>6,"name"=>"ACTIVIDADES ARTISTICAS- DEPORTIVAS O DE DIVULGACION","creditos"=>2]);
        Subject::create(["career_id"=>6,"name"=>"INGLES 3","creditos"=>0]);
        Subject::create(["career_id"=>6,"name"=>"LENGUAJE DE PROGRAMACION II","creditos"=>8]);
        Subject::create(["career_id"=>6,"name"=>"GEODESIA","creditos"=>8]);
        Subject::create(["career_id"=>6,"name"=>"INTEGRACION DE DATOS ESPACIALES","creditos"=>8]);
        Subject::create(["career_id"=>6,"name"=>"APLICACIONES DE TELEDETECCION","creditos"=>8]);
        Subject::create(["career_id"=>6,"name"=>"CARTOGRAFIA DIGITAL","creditos"=>8]);
        Subject::create(["career_id"=>6,"name"=>"HIDROGRAFIA","creditos"=>8]);
        Subject::create(["career_id"=>6,"name"=>"ARTE- CULTURA Y HUMANIDADES I","creditos"=>2]);
        Subject::create(["career_id"=>6,"name"=>"INGLES 4","creditos"=>0]);
        Subject::create(["career_id"=>6,"name"=>"GESTION PARA LA CREACION DE UNA EMPRESA","creditos"=>8]);
        Subject::create(["career_id"=>6,"name"=>"LENGUAJE DE PROGRAMACION III","creditos"=>8]);
        Subject::create(["career_id"=>6,"name"=>"SISTEMAS DE POSICIONAMIENTO","creditos"=>8]);
        Subject::create(["career_id"=>6,"name"=>"BASES DE DATOS ESPACIALES","creditos"=>10]);
        Subject::create(["career_id"=>6,"name"=>"ANALISIS ESPACIAL DEL MEDIO AMBIENTE","creditos"=>5]);
        Subject::create(["career_id"=>6,"name"=>"SISTEMAS HIDROLOGICOS","creditos"=>8]);
        Subject::create(["career_id"=>6,"name"=>"LIDERAZGO Y EMPRENDIMIENTO","creditos"=>3]);
        Subject::create(["career_id"=>6,"name"=>"INGLES 5","creditos"=>0]);
        Subject::create(["career_id"=>6,"name"=>"VALUACION INMOBILIARIA SOBRE EL TERRITORIO","creditos"=>5]);
        Subject::create(["career_id"=>6,"name"=>"PLANEACION Y DISEÑO DE SISTEMAS","creditos"=>5]);
        Subject::create(["career_id"=>6,"name"=>"DESARROLLO DE PROYECTO DE INGENIERIA","creditos"=>5]);
        Subject::create(["career_id"=>6,"name"=>"APLICACIONES DE GEODESIA Y POSICIONAMIENTO","creditos"=>8]);
        Subject::create(["career_id"=>6,"name"=>"APLICACIONES DE SISTEMAS DE INFORMACION GEOGRAFICOS","creditos"=>8]);
        Subject::create(["career_id"=>6,"name"=>"URBANISMO Y ORDENAMIENTO TERRITORIAL","creditos"=>5]);
        Subject::create(["career_id"=>6,"name"=>"AGRICULTURA DE PRECISION","creditos"=>8]);
        Subject::create(["career_id"=>6,"name"=>"GESTION DE PROYECTOS","creditos"=>3]);
        Subject::create(["career_id"=>6,"name"=>"SISTEMAS CATASTRALES","creditos"=>5]);
        Subject::create(["career_id"=>6,"name"=>"DIFUSION DE DATOS ESPACIALES EN INTERNET","creditos"=>8]);
        Subject::create(["career_id"=>6,"name"=>"ESTRUCTURAS DE DATOS GEOMETRICOS","creditos"=>8]);
        Subject::create(["career_id"=>6,"name"=>"SEMINARIO DE TITULACION","creditos"=>2]);
        Subject::create(["career_id"=>6,"name"=>"MODELOS DIGITALES DE TERRENO","creditos"=>8]);
        Subject::create(["career_id"=>6,"name"=>"INTELIGENCIA ARTIFICIAL Y RECONOCIMIENTO DE PATRONES","creditos"=>8]);
        Subject::create(["career_id"=>6,"name"=>"LEGISLACION PARA EL USO DE DATOS GEOESPACIALES","creditos"=>8]);
        Subject::create(["career_id"=>6,"name"=>"MODELADO EN OBRAS HIDRAULICAS","creditos"=>8]);
        Subject::create(["career_id"=>6,"name"=>"ARTE- CULTURA Y HUMANIDADES II","creditos"=>2]);
        Subject::create(["career_id"=>6,"name"=>"GEOESTADISTICA","creditos"=>8]);
        Subject::create(["career_id"=>6,"name"=>"MODELIZACION GEOMETRICA 3D","creditos"=>8]);
        Subject::create(["career_id"=>6,"name"=>"MINERIA DE DATOS ESPACIALES","creditos"=>8]);
        Subject::create(["career_id"=>6,"name"=>"DELIMITACION TERRITORIAL","creditos"=>5]);
        Subject::create(["career_id"=>7,"name"=>"GEOMETRIA Y TRIGONOMETRIA","creditos"=>0]);
        Subject::create(["career_id"=>7,"name"=>"QUIMICA A","creditos"=>8]);
        Subject::create(["career_id"=>7,"name"=>"ALGEBRA A","creditos"=>8]);
        Subject::create(["career_id"=>7,"name"=>"SEMINARIO DE ORIENTACION ING. AMBIENTAL","creditos"=>0]);
        Subject::create(["career_id"=>7,"name"=>"COMPUTACION APLICADA A","creditos"=>6]);
        Subject::create(["career_id"=>7,"name"=>"CRISTALOGRAFIA","creditos"=>5]);
        Subject::create(["career_id"=>7,"name"=>"GEOLOGIA BASICA I","creditos"=>10]);
        Subject::create(["career_id"=>7,"name"=>"METODOLOGIA DE LA INVESTIGACION","creditos"=>4]);
        Subject::create(["career_id"=>7,"name"=>"TECNICAS DE COMUNICACION ORAL Y ESCRITA","creditos"=>5]);
        Subject::create(["career_id"=>7,"name"=>"INGLES 1","creditos"=>0]);
        Subject::create(["career_id"=>7,"name"=>"CALCULO A","creditos"=>8]);
        Subject::create(["career_id"=>7,"name"=>"ALGEBRA B","creditos"=>8]);
        Subject::create(["career_id"=>7,"name"=>"DIBUJO GEOLOGICO ESTRUCTURAL","creditos"=>5]);
        Subject::create(["career_id"=>7,"name"=>"COMPUTACION APLICADA B","creditos"=>6]);
        Subject::create(["career_id"=>7,"name"=>"MINERALOGIA","creditos"=>5]);
        Subject::create(["career_id"=>7,"name"=>"GEOLOGIA BASICA II","creditos"=>10]);
        Subject::create(["career_id"=>7,"name"=>"SEDIMENTOLOGIA","creditos"=>6]);
        Subject::create(["career_id"=>7,"name"=>"INGLES 2","creditos"=>0]);
        Subject::create(["career_id"=>7,"name"=>"CALCULO B","creditos"=>8]);
        Subject::create(["career_id"=>7,"name"=>"FISICA A","creditos"=>8]);
        Subject::create(["career_id"=>7,"name"=>"GEOMORFOLOGIA","creditos"=>6]);
        Subject::create(["career_id"=>7,"name"=>"MINEROLOGIA OPTICA","creditos"=>9]);
        Subject::create(["career_id"=>7,"name"=>"TOPOGRAFIA APLICADA Y PRACTICAS","creditos"=>8]);
        Subject::create(["career_id"=>7,"name"=>"ESTRATIGRAFIA","creditos"=>6]);
        Subject::create(["career_id"=>7,"name"=>"TENDENCIAS SOCIALES","creditos"=>2]);
        Subject::create(["career_id"=>7,"name"=>"INGLES 3","creditos"=>0]);
        Subject::create(["career_id"=>7,"name"=>"HIDROLOGIA","creditos"=>6]);
        Subject::create(["career_id"=>7,"name"=>"FISICA C","creditos"=>6]);
        Subject::create(["career_id"=>7,"name"=>"GEOLOGIA ESTRUCTURAL I","creditos"=>6]);
        Subject::create(["career_id"=>7,"name"=>"PETROLOGIA Y PETROGRAFIA IGNEA","creditos"=>11]);
        Subject::create(["career_id"=>7,"name"=>"PROBABILIDAD Y ESTADISTICA","creditos"=>8]);
        Subject::create(["career_id"=>7,"name"=>"PALEONTOLOGIA","creditos"=>6]);
        Subject::create(["career_id"=>7,"name"=>"GESTION Y DESARROLLO SOCIAL","creditos"=>2]);
        Subject::create(["career_id"=>7,"name"=>"INGLES 4","creditos"=>0]);
        Subject::create(["career_id"=>7,"name"=>"AGUA SUBTERRANEA","creditos"=>8]);
        Subject::create(["career_id"=>7,"name"=>"GEOQUIMICA","creditos"=>8]);
        Subject::create(["career_id"=>7,"name"=>"GEOLOGIA ESTRUCTURAL II","creditos"=>8]);
        Subject::create(["career_id"=>7,"name"=>"PETROLOGIA Y PETROGRAFIA SEDIMENTARIA","creditos"=>8]);
        Subject::create(["career_id"=>7,"name"=>"GEOLOGIA HISTORICA","creditos"=>8]);
        Subject::create(["career_id"=>7,"name"=>"ARTE- CULTURA Y HUMANIDADES I","creditos"=>2]);
        Subject::create(["career_id"=>7,"name"=>"INGLES 5","creditos"=>0]);
        Subject::create(["career_id"=>7,"name"=>"ADMINISTRACION Y COACHING EMPRESARIAL","creditos"=>8]);
        Subject::create(["career_id"=>7,"name"=>"EXCURSIONES GEOLOGICAS I","creditos"=>10]);
        Subject::create(["career_id"=>7,"name"=>"GEOMORFOLOGIA ESTRUCTURAL","creditos"=>6]);
        Subject::create(["career_id"=>7,"name"=>"PETROLOGIA Y PETROGRAFIA METAMORFICA","creditos"=>10]);
        Subject::create(["career_id"=>7,"name"=>"GEOTECTONICA","creditos"=>8]);
        Subject::create(["career_id"=>7,"name"=>"METODOS DE PERFORACION","creditos"=>8]);
        Subject::create(["career_id"=>7,"name"=>"ARTE- CULTURA Y HUMANIDADES II","creditos"=>2]);
        Subject::create(["career_id"=>7,"name"=>"FORMULACION Y GESTION DE PROYECTOS","creditos"=>7]);
        Subject::create(["career_id"=>7,"name"=>"CONTAMINACION DEL AGUA SUBTERRANEA","creditos"=>8]);
        Subject::create(["career_id"=>7,"name"=>"DESARROLLO DE PROYECTOS GEOLOGICOS I","creditos"=>10]);
        Subject::create(["career_id"=>7,"name"=>"GEOLOGIA DE MEXICO","creditos"=>8]);
        Subject::create(["career_id"=>7,"name"=>"YACIMIENTOS MINERALES","creditos"=>10]);
        Subject::create(["career_id"=>7,"name"=>"GEOFISICA APLICADA","creditos"=>5]);
        Subject::create(["career_id"=>7,"name"=>"LIDERAZGO Y EMPRENDIMIENTO","creditos"=>3]);
        Subject::create(["career_id"=>7,"name"=>"EXCURSIONES GEOLOGICAS II","creditos"=>10]);
        Subject::create(["career_id"=>7,"name"=>"DESARROLLO DE PROYECTOS GEOLOGICOS II","creditos"=>10]);
        Subject::create(["career_id"=>7,"name"=>"GEOLOGIA DEL PETROLEO","creditos"=>6]);
        Subject::create(["career_id"=>7,"name"=>"GEOLOGIA ECONOMICA","creditos"=>8]);
        Subject::create(["career_id"=>7,"name"=>"COMPUTACION APLICADA C","creditos"=>6]);
        Subject::create(["career_id"=>7,"name"=>"GEOTECNIA I","creditos"=>12]);
        Subject::create(["career_id"=>7,"name"=>"ACTIVIDADES ARTISTICAS- DEPORTIVAS O DE DIVULGACION","creditos"=>2]);
        Subject::create(["career_id"=>7,"name"=>"METODOS DE EXPLORACION","creditos"=>8]);
        Subject::create(["career_id"=>7,"name"=>"GEOLOGIA AMBIENTAL","creditos"=>8]);
        Subject::create(["career_id"=>7,"name"=>"PRACTICAS PROFESIONALES I","creditos"=>15]);
        Subject::create(["career_id"=>7,"name"=>"PRACTICAS PROFESIONALES II","creditos"=>15]);
        Subject::create(["career_id"=>7,"name"=>"GEOLOGIA APLICADA A LA INGENIERIA CIVIL","creditos"=>10]);
        Subject::create(["career_id"=>8,"name"=>"QUIMICA A","creditos"=>8]);
        Subject::create(["career_id"=>8,"name"=>"PENSAMIENTO ALGORITMICO","creditos"=>8]);
        Subject::create(["career_id"=>8,"name"=>"ALGEBRA A","creditos"=>8]);
        Subject::create(["career_id"=>8,"name"=>"HERRAMIENTAS DE SOFTWARE","creditos"=>8]);
        Subject::create(["career_id"=>8,"name"=>"FUNDAMENTOS DE DISEÑO DIGITAL","creditos"=>8]);
        Subject::create(["career_id"=>8,"name"=>"SEMINARIO DE ORIENTACION I.I.","creditos"=>0]);
        Subject::create(["career_id"=>8,"name"=>"METODOLOGIA DE LA INVESTIGACION","creditos"=>4]);
        Subject::create(["career_id"=>8,"name"=>"FISICA A","creditos"=>8]);
        Subject::create(["career_id"=>8,"name"=>"GEOMETRIA Y TRIGONOMETRIA","creditos"=>0]);
        Subject::create(["career_id"=>8,"name"=>"ESTRUCTURAS DE DATOS I","creditos"=>8]);
        Subject::create(["career_id"=>8,"name"=>"ALGEBRA B","creditos"=>8]);
        Subject::create(["career_id"=>8,"name"=>"CALCULO A","creditos"=>8]);
        Subject::create(["career_id"=>8,"name"=>"MATEMATICAS DISCRETAS I","creditos"=>8]);
        Subject::create(["career_id"=>8,"name"=>"TECNICAS DE COMUNICACION ORAL Y ESCRITA","creditos"=>5]);
        Subject::create(["career_id"=>8,"name"=>"INGENIERIA DE REQUERIMIENTOS","creditos"=>10]);
        Subject::create(["career_id"=>8,"name"=>"LENGUAJES DE PROGRAMACION","creditos"=>8]);
        Subject::create(["career_id"=>8,"name"=>"ESTRUCTURAS DE DATOS II","creditos"=>8]);
        Subject::create(["career_id"=>8,"name"=>"CALCULO D","creditos"=>8]);
        Subject::create(["career_id"=>8,"name"=>"CALCULO C","creditos"=>6]);
        Subject::create(["career_id"=>8,"name"=>"DISEÑO DIGITAL","creditos"=>10]);
        Subject::create(["career_id"=>8,"name"=>"ACTIVIDADES ARTISTICAS- DEPORTIVAS O DE DIVULGACION","creditos"=>2]);
        Subject::create(["career_id"=>8,"name"=>"INGLES 1","creditos"=>5]);
        Subject::create(["career_id"=>8,"name"=>"MODELADO MATEMATICO","creditos"=>8]);
        Subject::create(["career_id"=>8,"name"=>"TECNOLOGIA ORIENTADA A OBJETOS","creditos"=>8]);
        Subject::create(["career_id"=>8,"name"=>"ANALISIS NUMERICO","creditos"=>8]);
        Subject::create(["career_id"=>8,"name"=>"ARQUITECTURA DE COMPUTADORAS A","creditos"=>10]);
        Subject::create(["career_id"=>8,"name"=>"LEGISLACION E INFORMATICA","creditos"=>6]);
        Subject::create(["career_id"=>8,"name"=>"TENDENCIAS SOCIALES","creditos"=>2]);
        Subject::create(["career_id"=>8,"name"=>"INGLES 2","creditos"=>5]);
        Subject::create(["career_id"=>8,"name"=>"INGENIERIA DE SOFTWARE A","creditos"=>10]);
        Subject::create(["career_id"=>8,"name"=>"MODELOS MATEMATICOS B","creditos"=>6]);
        Subject::create(["career_id"=>8,"name"=>"INTERFACES GRAFICAS CON APLICACIONES","creditos"=>8]);
        Subject::create(["career_id"=>8,"name"=>"PROBABILIDAD Y ESTADISTICA","creditos"=>8]);
        Subject::create(["career_id"=>8,"name"=>"ECONOMIA Y FINANZAS","creditos"=>6]);
        Subject::create(["career_id"=>8,"name"=>"GESTION Y DESARROLLO SOCIAL","creditos"=>2]);
        Subject::create(["career_id"=>8,"name"=>"INGLES 3","creditos"=>5]);
        Subject::create(["career_id"=>8,"name"=>"INGENIERIA DE SOFTWARE B","creditos"=>8]);
        Subject::create(["career_id"=>8,"name"=>"GRAFICACION POR COMPUTADORA","creditos"=>8]);
        Subject::create(["career_id"=>8,"name"=>"GRAFOS","creditos"=>10]);
        Subject::create(["career_id"=>8,"name"=>"SISTEMAS OPERATIVOS","creditos"=>8]);
        Subject::create(["career_id"=>8,"name"=>"ESTRUCTURAS DE ARCHIVOS","creditos"=>8]);
        Subject::create(["career_id"=>8,"name"=>"ARTE- CULTURA Y HUMANIDADES I","creditos"=>2]);
        Subject::create(["career_id"=>8,"name"=>"INGLES 4","creditos"=>5]);
        Subject::create(["career_id"=>8,"name"=>"INGENIERIA DE SOFTWARE C","creditos"=>8]);
        Subject::create(["career_id"=>8,"name"=>"ADMINISTRACION DE SISTEMAS","creditos"=>8]);
        Subject::create(["career_id"=>8,"name"=>"COMPILADORES E INTERPRETES A","creditos"=>10]);
        Subject::create(["career_id"=>8,"name"=>"REDES A","creditos"=>12]);
        Subject::create(["career_id"=>8,"name"=>"BASES DE DATOS A","creditos"=>10]);
        Subject::create(["career_id"=>8,"name"=>"ADMINISTRACION","creditos"=>8]);
        Subject::create(["career_id"=>8,"name"=>"LIDERAZGO Y EMPRENDIMIENTO","creditos"=>3]);
        Subject::create(["career_id"=>8,"name"=>"INGLES 5","creditos"=>5]);
        Subject::create(["career_id"=>8,"name"=>"FUNDAMENTOS DE DESARROLLO WEB","creditos"=>8]);
        Subject::create(["career_id"=>8,"name"=>"GRAFICACION POR COMPUTADORA B","creditos"=>10]);
        Subject::create(["career_id"=>8,"name"=>"VISION COMPUTACIONAL","creditos"=>8]);
        Subject::create(["career_id"=>8,"name"=>"SISTEMAS OPERATIVOS B","creditos"=>10]);
        Subject::create(["career_id"=>8,"name"=>"ADMINISTRACION DE BASES DE DATOS","creditos"=>8]);
        Subject::create(["career_id"=>8,"name"=>"PROYECTO INTEGRADOR","creditos"=>10]);
        Subject::create(["career_id"=>8,"name"=>"ARTE- CULTURA Y HUMANIDADES II","creditos"=>2]);
        Subject::create(["career_id"=>8,"name"=>"APLICACIONES WEB INTERACTIVAS","creditos"=>8]);
        Subject::create(["career_id"=>8,"name"=>"FUNDAMENTOS DE INTELIGENCIA ARTIFICIAL","creditos"=>8]);
        Subject::create(["career_id"=>8,"name"=>"SISTEMAS DE INFORMACION A","creditos"=>10]);
        Subject::create(["career_id"=>8,"name"=>"TELEMATICA A","creditos"=>8]);
        Subject::create(["career_id"=>8,"name"=>"REDES B","creditos"=>10]);
        Subject::create(["career_id"=>8,"name"=>"BASES DE DATOS B","creditos"=>10]);
        Subject::create(["career_id"=>8,"name"=>"ADMINISTRACION INFORMATICA A","creditos"=>8]);
        Subject::create(["career_id"=>8,"name"=>"PRACTICAS PROFESIONALES I","creditos"=>15]);
        Subject::create(["career_id"=>8,"name"=>"SUPERCOMPUTO","creditos"=>8]);
        Subject::create(["career_id"=>8,"name"=>"COMPUTACION UBICUA","creditos"=>8]);
        Subject::create(["career_id"=>8,"name"=>"SISTEMAS DE INFORMACION B","creditos"=>6]);
        Subject::create(["career_id"=>8,"name"=>"PRINCIPIOS DE SEGURIDAD INFORMATICA","creditos"=>8]);
        Subject::create(["career_id"=>8,"name"=>"SEMINARIO DE EGRESO","creditos"=>0]);
        Subject::create(["career_id"=>8,"name"=>"TECNOLOGIA INFORMATICA","creditos"=>6]);
        Subject::create(["career_id"=>8,"name"=>"ADMINISTRACION INFORMATICA B","creditos"=>8]);
        Subject::create(["career_id"=>8,"name"=>"SEMINARIO I.I.","creditos"=>1]);
        Subject::create(["career_id"=>9,"name"=>"ALGEBRA A","creditos"=>8]);
        Subject::create(["career_id"=>9,"name"=>"PRINCIPIOS DE ADMINISTRACION","creditos"=>6]);
        Subject::create(["career_id"=>9,"name"=>"QUIMICA A","creditos"=>8]);
        Subject::create(["career_id"=>9,"name"=>"GEOMETRIA DESCRIPTIVA","creditos"=>5]);
        Subject::create(["career_id"=>9,"name"=>"GEOMETRIA Y TRIGONOMETRIA","creditos"=>0]);
        Subject::create(["career_id"=>9,"name"=>"FISICA A","creditos"=>8]);
        Subject::create(["career_id"=>9,"name"=>"CALCULO A","creditos"=>8]);
        Subject::create(["career_id"=>9,"name"=>"SEMINARIO DE ORIENTACION IM","creditos"=>1]);
        Subject::create(["career_id"=>9,"name"=>"METODOLOGIA DE LA INVESTIGACION","creditos"=>4]);
        Subject::create(["career_id"=>9,"name"=>"ALGEBRA B","creditos"=>8]);
        Subject::create(["career_id"=>9,"name"=>"HABILIDADES SOCIO AFECTIVAS Y ETICAS","creditos"=>3]);
        Subject::create(["career_id"=>9,"name"=>"DIBUJO EN INGENIERIA MECANICA","creditos"=>8]);
        Subject::create(["career_id"=>9,"name"=>"CALCULO C","creditos"=>6]);
        Subject::create(["career_id"=>9,"name"=>"ESTATICA","creditos"=>8]);
        Subject::create(["career_id"=>9,"name"=>"FISICA B","creditos"=>8]);
        Subject::create(["career_id"=>9,"name"=>"CALCULO B","creditos"=>8]);
        Subject::create(["career_id"=>9,"name"=>"INGLES 1","creditos"=>0]);
        Subject::create(["career_id"=>9,"name"=>"PROBABILIDAD E INFERENCIA ESTADISTICA","creditos"=>10]);
        Subject::create(["career_id"=>9,"name"=>"INGENIERIA DE MATERIALES I","creditos"=>6]);
        Subject::create(["career_id"=>9,"name"=>"DIBUJO ASISTIDO POR COMPUTADORA","creditos"=>3]);
        Subject::create(["career_id"=>9,"name"=>"DINAMICA","creditos"=>8]);
        Subject::create(["career_id"=>9,"name"=>"MECANICA DE MATERIALES I","creditos"=>11]);
        Subject::create(["career_id"=>9,"name"=>"CALCULO D","creditos"=>8]);
        Subject::create(["career_id"=>9,"name"=>"INGLES 2","creditos"=>0]);
        Subject::create(["career_id"=>9,"name"=>"INVESTIGACION DE OPERACIONES I","creditos"=>6]);
        Subject::create(["career_id"=>9,"name"=>"INTRODUCCIÓN A LA PROGRAMACIÓN","creditos"=>8]);
        Subject::create(["career_id"=>9,"name"=>"INGENIERIA DE MATERIALES II","creditos"=>7]);
        Subject::create(["career_id"=>9,"name"=>"METROLOGIA","creditos"=>8]);
        Subject::create(["career_id"=>9,"name"=>"CINEMATICA DE LAS MAQUINAS","creditos"=>10]);
        Subject::create(["career_id"=>9,"name"=>"MECANICA DE MATERIALES II","creditos"=>6]);
        Subject::create(["career_id"=>9,"name"=>"INGLES 3","creditos"=>0]);
        Subject::create(["career_id"=>9,"name"=>"TECNICAS DE COMUNICACION ORAL Y ESCRITA","creditos"=>5]);
        Subject::create(["career_id"=>9,"name"=>"SISTEMAS DE PRODUCCION","creditos"=>8]);
        Subject::create(["career_id"=>9,"name"=>"ANALISIS NUMERICO","creditos"=>6]);
        Subject::create(["career_id"=>9,"name"=>"PROCESOS DE FABRICACION I","creditos"=>8]);
        Subject::create(["career_id"=>9,"name"=>"METODOLOGIA DEL DISEÑO","creditos"=>6]);
        Subject::create(["career_id"=>9,"name"=>"TERMODINAMICA","creditos"=>11]);
        Subject::create(["career_id"=>9,"name"=>"ELECTROTECNIA PARA INGENIERIA I","creditos"=>9]);
        Subject::create(["career_id"=>9,"name"=>"INGLES 4","creditos"=>0]);
        Subject::create(["career_id"=>9,"name"=>"PROCESOS DE FABRICACION II","creditos"=>6]);
        Subject::create(["career_id"=>9,"name"=>"VIBRACIONES MECANICAS","creditos"=>10]);
        Subject::create(["career_id"=>9,"name"=>"DISEÑO MECANICO A","creditos"=>11]);
        Subject::create(["career_id"=>9,"name"=>"MAQUINAS TERMICAS","creditos"=>11]);
        Subject::create(["career_id"=>9,"name"=>"ELECTROTECNIA PARA INGENIERIA II","creditos"=>10]);
        Subject::create(["career_id"=>9,"name"=>"INGLES 5","creditos"=>0]);
        Subject::create(["career_id"=>9,"name"=>"CONTROL DE CALIDAD","creditos"=>6]);
        Subject::create(["career_id"=>9,"name"=>"PROCESOS DE FABRICACION III","creditos"=>8]);
        Subject::create(["career_id"=>9,"name"=>"ADMINISTRACION DE PROYECTOS","creditos"=>6]);
        Subject::create(["career_id"=>9,"name"=>"DISEÑO MECANICO B","creditos"=>9]);
        Subject::create(["career_id"=>9,"name"=>"MECANICA DE FLUIDOS","creditos"=>11]);
        Subject::create(["career_id"=>9,"name"=>"SISTEMAS DE CONTROL Y AUTOMATIZACION","creditos"=>7]);
        Subject::create(["career_id"=>9,"name"=>"VALIDACION DE LA LENGUA EXTRANJERA","creditos"=>0]);
        Subject::create(["career_id"=>9,"name"=>"LIDERAZGO Y EMPRENDIMIENTO","creditos"=>3]);
        Subject::create(["career_id"=>9,"name"=>"CONTROL NUMERICO COMPUTARIZADO","creditos"=>8]);
        Subject::create(["career_id"=>9,"name"=>"INGENIERIA Y GESTION AMBIENTAL","creditos"=>3]);
        Subject::create(["career_id"=>9,"name"=>"METODO DE LOS ELEMENTOS FINITOS","creditos"=>9]);
        Subject::create(["career_id"=>9,"name"=>"FENOMENOS DE TRANSPORTE","creditos"=>10]);
        Subject::create(["career_id"=>9,"name"=>"CIRCUITOS HIDRAULICOS Y NEUMATICOS","creditos"=>10]);
        Subject::create(["career_id"=>9,"name"=>"TOPICOS AVANZADOS DE FABRICACION","creditos"=>6]);
        Subject::create(["career_id"=>9,"name"=>"MANTENIMIENTO INDUSTRIAL","creditos"=>6]);
        Subject::create(["career_id"=>9,"name"=>"PROYECTO INTEGRADOR IM","creditos"=>10]);
        Subject::create(["career_id"=>9,"name"=>"SISTEMAS HIDROMECANICOS A","creditos"=>7]);
        Subject::create(["career_id"=>9,"name"=>"SEMINARIO","creditos"=>2]);
        Subject::create(["career_id"=>9,"name"=>"INSTALACIONES INDUSTRIALES","creditos"=>6]);
        Subject::create(["career_id"=>9,"name"=>"PRACTICAS PROFESIONALES I","creditos"=>15]);
        Subject::create(["career_id"=>9,"name"=>"SEMINARIO DE EGRESO","creditos"=>0]);
        Subject::create(["career_id"=>10,"name"=>"PRINCIPIOS DE ADMINISTRACION","creditos"=>6]);
        Subject::create(["career_id"=>10,"name"=>"ALGEBRA A","creditos"=>8]);
        Subject::create(["career_id"=>10,"name"=>"FISICA A","creditos"=>8]);
        Subject::create(["career_id"=>10,"name"=>"CALCULO A","creditos"=>8]);
        Subject::create(["career_id"=>10,"name"=>"GEOMETRIA Y TRIGONOMETRIA","creditos"=>0]);
        Subject::create(["career_id"=>10,"name"=>"GEOMETRIA DESCRIPTIVA","creditos"=>5]);
        Subject::create(["career_id"=>10,"name"=>"QUIMICA A","creditos"=>8]);
        Subject::create(["career_id"=>10,"name"=>"METODOLOGIA DE LA INVESTIGACION","creditos"=>4]);
        Subject::create(["career_id"=>10,"name"=>"SEMINARIO DE ORIENTACION IMA","creditos"=>1]);
        Subject::create(["career_id"=>10,"name"=>"ALGEBRA B","creditos"=>8]);
        Subject::create(["career_id"=>10,"name"=>"CALCULO D","creditos"=>8]);
        Subject::create(["career_id"=>10,"name"=>"FISICA B","creditos"=>8]);
        Subject::create(["career_id"=>10,"name"=>"CALCULO B","creditos"=>8]);
        Subject::create(["career_id"=>10,"name"=>"ESTATICA","creditos"=>8]);
        Subject::create(["career_id"=>10,"name"=>"DIBUJO EN INGENIERIA MECANICA","creditos"=>8]);
        Subject::create(["career_id"=>10,"name"=>"INGLES 1","creditos"=>0]);
        Subject::create(["career_id"=>10,"name"=>"INTRODUCCION A LA CONTABILIDAD","creditos"=>6]);
        Subject::create(["career_id"=>10,"name"=>"INTRODUCCIÓN A LA PROGRAMACIÓN","creditos"=>8]);
        Subject::create(["career_id"=>10,"name"=>"TERMODINAMICA","creditos"=>11]);
        Subject::create(["career_id"=>10,"name"=>"CALCULO C","creditos"=>6]);
        Subject::create(["career_id"=>10,"name"=>"DINAMICA","creditos"=>8]);
        Subject::create(["career_id"=>10,"name"=>"INGENIERIA DE MATERIALES I","creditos"=>6]);
        Subject::create(["career_id"=>10,"name"=>"INGLES 2","creditos"=>0]);
        Subject::create(["career_id"=>10,"name"=>"TECNICAS DE COMUNICACION ORAL Y ESCRITA","creditos"=>5]);
        Subject::create(["career_id"=>10,"name"=>"CONTABILIDAD INDUSTRIAL","creditos"=>6]);
        Subject::create(["career_id"=>10,"name"=>"INVESTIGACION DE OPERACIONES I","creditos"=>6]);
        Subject::create(["career_id"=>10,"name"=>"ANALISIS NUMERICO","creditos"=>6]);
        Subject::create(["career_id"=>10,"name"=>"MECANICA DE MATERIALES I","creditos"=>11]);
        Subject::create(["career_id"=>10,"name"=>"MECANICA DE FLUIDOS","creditos"=>11]);
        Subject::create(["career_id"=>10,"name"=>"INGENIERIA DE MATERIALES II","creditos"=>7]);
        Subject::create(["career_id"=>10,"name"=>"INGLES 3","creditos"=>0]);
        Subject::create(["career_id"=>10,"name"=>"DIBUJO ASISTIDO POR COMPUTADORA","creditos"=>3]);
        Subject::create(["career_id"=>10,"name"=>"CONTABILIDAD ADMINISTRATIVA","creditos"=>6]);
        Subject::create(["career_id"=>10,"name"=>"INVESTIGACION DE OPERACIONES II","creditos"=>6]);
        Subject::create(["career_id"=>10,"name"=>"MAQUINAS TERMICAS","creditos"=>11]);
        Subject::create(["career_id"=>10,"name"=>"CINEMATICA DE LAS MAQUINAS","creditos"=>10]);
        Subject::create(["career_id"=>10,"name"=>"MECANICA DE MATERIALES II","creditos"=>6]);
        Subject::create(["career_id"=>10,"name"=>"ELECTROTECNIA PARA INGENIERIA I","creditos"=>9]);
        Subject::create(["career_id"=>10,"name"=>"INGLES 4","creditos"=>0]);
        Subject::create(["career_id"=>10,"name"=>"ECONOMIA","creditos"=>6]);
        Subject::create(["career_id"=>10,"name"=>"SISTEMAS DE PRODUCCION I","creditos"=>6]);
        Subject::create(["career_id"=>10,"name"=>"PROBABILIDAD E INFERENCIA ESTADISTICA","creditos"=>10]);
        Subject::create(["career_id"=>10,"name"=>"FENOMENOS DE TRANSPORTE","creditos"=>10]);
        Subject::create(["career_id"=>10,"name"=>"ELECTROTECNIA PARA INGENIERIA II","creditos"=>10]);
        Subject::create(["career_id"=>10,"name"=>"PROCESOS DE FABRICACION I","creditos"=>8]);
        Subject::create(["career_id"=>10,"name"=>"INGLES 5","creditos"=>0]);
        Subject::create(["career_id"=>10,"name"=>"ADMINISTRACION DE PERSONAL","creditos"=>6]);
        Subject::create(["career_id"=>10,"name"=>"SISTEMAS DE PRODUCCION II","creditos"=>6]);
        Subject::create(["career_id"=>10,"name"=>"METROLOGIA","creditos"=>8]);
        Subject::create(["career_id"=>10,"name"=>"INGENIERIA DE METODOS","creditos"=>8]);
        Subject::create(["career_id"=>10,"name"=>"DISEÑO MECANICO A","creditos"=>11]);
        Subject::create(["career_id"=>10,"name"=>"SISTEMAS DE CONTROL Y AUTOMATIZACION","creditos"=>7]);
        Subject::create(["career_id"=>10,"name"=>"VALIDACION DE LA LENGUA EXTRANJERA","creditos"=>0]);
        Subject::create(["career_id"=>10,"name"=>"GERENCIA EFECTIVA DE EMPRESAS","creditos"=>6]);
        Subject::create(["career_id"=>10,"name"=>"CONTROL DE CALIDAD","creditos"=>6]);
        Subject::create(["career_id"=>10,"name"=>"ADMINISTRACION DE PROYECTOS","creditos"=>6]);
        Subject::create(["career_id"=>10,"name"=>"INGENIERIA Y GESTION AMBIENTAL","creditos"=>3]);
        Subject::create(["career_id"=>10,"name"=>"DISEÑO MECANICO B","creditos"=>9]);
        Subject::create(["career_id"=>10,"name"=>"CIRCUITOS HIDRAULICOS Y NEUMATICOS","creditos"=>10]);
        Subject::create(["career_id"=>10,"name"=>"PROCESOS DE FABRICACION II","creditos"=>6]);
        Subject::create(["career_id"=>10,"name"=>"FORMULACION Y EVALUACION DE PROYECTOS","creditos"=>8]);
        Subject::create(["career_id"=>10,"name"=>"DISEÑO DE SISTEMAS DE PRODUCCION","creditos"=>6]);
        Subject::create(["career_id"=>10,"name"=>"SISTEMAS DE GESTION DE CALIDAD Y MEJORA CONTINUA","creditos"=>6]);
        Subject::create(["career_id"=>10,"name"=>"PROYECTO INTEGRADOR IMA","creditos"=>10]);
        Subject::create(["career_id"=>10,"name"=>"PROCESOS DE FABRICACION III","creditos"=>8]);
        Subject::create(["career_id"=>10,"name"=>"PRACTICAS PROFESIONALES I","creditos"=>15]);
        Subject::create(["career_id"=>10,"name"=>"SEMINARIO DE EGRESO","creditos"=>0]);
        Subject::create(["career_id"=>10,"name"=>"SEMINARIO","creditos"=>2]);
        Subject::create(["career_id"=>11,"name"=>"ALGEBRA A","creditos"=>8]);
        Subject::create(["career_id"=>11,"name"=>"GEOMETRIA DESCRIPTIVA","creditos"=>5]);
        Subject::create(["career_id"=>11,"name"=>"GEOMETRIA Y TRIGONOMETRIA","creditos"=>0]);
        Subject::create(["career_id"=>11,"name"=>"EXPERIMENTACION MECANICA ELECTRICA","creditos"=>5]);
        Subject::create(["career_id"=>11,"name"=>"CALCULO A","creditos"=>8]);
        Subject::create(["career_id"=>11,"name"=>"LIDERAZGO Y EMPRENDIMIENTO","creditos"=>3]);
        Subject::create(["career_id"=>11,"name"=>"FISICA A","creditos"=>8]);
        Subject::create(["career_id"=>11,"name"=>"QUIMICA A","creditos"=>8]);
        Subject::create(["career_id"=>11,"name"=>"SEMINARIO DE ORIENTACION IME","creditos"=>1]);
        Subject::create(["career_id"=>11,"name"=>"INGLES 1","creditos"=>0]);
        Subject::create(["career_id"=>11,"name"=>"ALGEBRA B","creditos"=>8]);
        Subject::create(["career_id"=>11,"name"=>"ELECTRICIDAD Y MAGNETISMO A","creditos"=>9]);
        Subject::create(["career_id"=>11,"name"=>"CALCULO C","creditos"=>6]);
        Subject::create(["career_id"=>11,"name"=>"CALCULO D","creditos"=>8]);
        Subject::create(["career_id"=>11,"name"=>"CALCULO B","creditos"=>8]);
        Subject::create(["career_id"=>11,"name"=>"ESTATICA","creditos"=>8]);
        Subject::create(["career_id"=>11,"name"=>"INGLES 2","creditos"=>0]);
        Subject::create(["career_id"=>11,"name"=>"INTRODUCCIÓN A LA PROGRAMACIÓN","creditos"=>8]);
        Subject::create(["career_id"=>11,"name"=>"DIBUJO EN INGENIERIA MECANICA","creditos"=>8]);
        Subject::create(["career_id"=>11,"name"=>"ELECTRICIDAD Y MAGNETISMO B","creditos"=>9]);
        Subject::create(["career_id"=>11,"name"=>"MATEMATICAS APLICADAS","creditos"=>6]);
        Subject::create(["career_id"=>11,"name"=>"DINAMICA","creditos"=>8]);
        Subject::create(["career_id"=>11,"name"=>"MATERIALES PARA INGENIERIA","creditos"=>9]);
        Subject::create(["career_id"=>11,"name"=>"INGLES 3","creditos"=>0]);
        Subject::create(["career_id"=>11,"name"=>"ANALISIS NUMERICO","creditos"=>6]);
        Subject::create(["career_id"=>11,"name"=>"DIBUJO ASISTIDO POR COMPUTADORA","creditos"=>3]);
        Subject::create(["career_id"=>11,"name"=>"CIRCUITOS ELECTRICOS A","creditos"=>12]);
        Subject::create(["career_id"=>11,"name"=>"PRINCIPIOS DE ADMINISTRACION","creditos"=>6]);
        Subject::create(["career_id"=>11,"name"=>"TERMODINAMICA","creditos"=>11]);
        Subject::create(["career_id"=>11,"name"=>"MECANICA DE MATERIALES I","creditos"=>11]);
        Subject::create(["career_id"=>11,"name"=>"INGLES 4","creditos"=>0]);
        Subject::create(["career_id"=>11,"name"=>"PROBABILIDAD E INFERENCIA ESTADISTICA","creditos"=>10]);
        Subject::create(["career_id"=>11,"name"=>"CIRCUITOS ELECTRICOS B","creditos"=>10]);
        Subject::create(["career_id"=>11,"name"=>"MAQUINAS TERMICAS","creditos"=>11]);
        Subject::create(["career_id"=>11,"name"=>"MECANICA DE FLUIDOS","creditos"=>11]);
        Subject::create(["career_id"=>11,"name"=>"MECANICA DE MATERIALES II","creditos"=>6]);
        Subject::create(["career_id"=>11,"name"=>"INGLES 5","creditos"=>0]);
        Subject::create(["career_id"=>11,"name"=>"ELECTRONICA APLICADA","creditos"=>12]);
        Subject::create(["career_id"=>11,"name"=>"MAQUINAS ELECTRICAS I","creditos"=>12]);
        Subject::create(["career_id"=>11,"name"=>"CONTROL DE CALIDAD","creditos"=>6]);
        Subject::create(["career_id"=>11,"name"=>"MODELADO Y SIMULACION DE SISTEMAS","creditos"=>7]);
        Subject::create(["career_id"=>11,"name"=>"FENOMENOS DE TRANSPORTE","creditos"=>10]);
        Subject::create(["career_id"=>11,"name"=>"VALIDACION DE LA LENGUA EXTRANJERA","creditos"=>0]);
        Subject::create(["career_id"=>11,"name"=>"INVESTIGACION DE OPERACIONES I","creditos"=>6]);
        Subject::create(["career_id"=>11,"name"=>"MAQUINAS ELECTRICAS II","creditos"=>12]);
        Subject::create(["career_id"=>11,"name"=>"DIAGRAMAS ELECTRICOS","creditos"=>3]);
        Subject::create(["career_id"=>11,"name"=>"INGENIERIA DE CONTROL I","creditos"=>8]);
        Subject::create(["career_id"=>11,"name"=>"SISTEMAS ELECTROHIDRAULICOS Y ELECTRONEUMATICOS","creditos"=>10]);
        Subject::create(["career_id"=>11,"name"=>"CINEMATICA DE LAS MAQUINAS","creditos"=>10]);
        Subject::create(["career_id"=>11,"name"=>"ANALISIS DE SISTEMAS DE POTENCIA","creditos"=>12]);
        Subject::create(["career_id"=>11,"name"=>"PROCESOS DE MANUFACTURA I","creditos"=>10]);
        Subject::create(["career_id"=>11,"name"=>"AUTOMATIZACION INDUSTRIAL","creditos"=>8]);
        Subject::create(["career_id"=>11,"name"=>"SISTEMAS HIDROMECANICOS A","creditos"=>7]);
        Subject::create(["career_id"=>11,"name"=>"DISEÑO MECANICO A","creditos"=>11]);
        Subject::create(["career_id"=>11,"name"=>"USO EFICIENTE E IMPACTO AMBIENTAL DE LA ENERGIA","creditos"=>6]);
        Subject::create(["career_id"=>11,"name"=>"INSTALACIONES ELECTRICAS B","creditos"=>10]);
        Subject::create(["career_id"=>11,"name"=>"PROCESOS DE MANUFACTURA II","creditos"=>8]);
        Subject::create(["career_id"=>11,"name"=>"PROYECTO INTEGRADOR IME","creditos"=>10]);
        Subject::create(["career_id"=>11,"name"=>"METODO DE LOS ELEMENTOS FINITOS","creditos"=>9]);
        Subject::create(["career_id"=>11,"name"=>"PRACTICAS PROFESIONALES I","creditos"=>15]);
        Subject::create(["career_id"=>11,"name"=>"SEMINARIO DE EGRESO","creditos"=>0]);
        Subject::create(["career_id"=>11,"name"=>"SEMINARIO","creditos"=>2]);
        Subject::create(["career_id"=>12,"name"=>"HABILIDADES SOCIO AFECTIVAS Y ETICAS","creditos"=>3]);
        Subject::create(["career_id"=>12,"name"=>"ALGEBRA A","creditos"=>8]);
        Subject::create(["career_id"=>12,"name"=>"CALCULO A","creditos"=>8]);
        Subject::create(["career_id"=>12,"name"=>"GEOMETRIA Y TRIGONOMETRIA","creditos"=>0]);
        Subject::create(["career_id"=>12,"name"=>"FISICA A","creditos"=>8]);
        Subject::create(["career_id"=>12,"name"=>"DIBUJO EN INGENIERIA MECANICA","creditos"=>8]);
        Subject::create(["career_id"=>12,"name"=>"QUIMICA A","creditos"=>8]);
        Subject::create(["career_id"=>12,"name"=>"METODOLOGIA DE LA INVESTIGACION","creditos"=>4]);
        Subject::create(["career_id"=>12,"name"=>"SEMINARIO DE ORIENTACION IMT","creditos"=>1]);
        Subject::create(["career_id"=>12,"name"=>"ALGEBRA B","creditos"=>8]);
        Subject::create(["career_id"=>12,"name"=>"CALCULO D","creditos"=>8]);
        Subject::create(["career_id"=>12,"name"=>"ELECTROTECNIA PARA INGENIERIA I","creditos"=>9]);
        Subject::create(["career_id"=>12,"name"=>"CALCULO B","creditos"=>8]);
        Subject::create(["career_id"=>12,"name"=>"ESTATICA","creditos"=>8]);
        Subject::create(["career_id"=>12,"name"=>"MATERIALES PARA INGENIERIA","creditos"=>9]);
        Subject::create(["career_id"=>12,"name"=>"INGLES 1","creditos"=>0]);
        Subject::create(["career_id"=>12,"name"=>"TERMODINAMICA","creditos"=>11]);
        Subject::create(["career_id"=>12,"name"=>"CIRCUITOS ELECTRICOS A","creditos"=>12]);
        Subject::create(["career_id"=>12,"name"=>"DINAMICA","creditos"=>8]);
        Subject::create(["career_id"=>12,"name"=>"MECANICA DE MATERIALES I","creditos"=>11]);
        Subject::create(["career_id"=>12,"name"=>"TECNICAS DE COMUNICACION ORAL Y ESCRITA","creditos"=>5]);
        Subject::create(["career_id"=>12,"name"=>"INGLES 2","creditos"=>0]);
        Subject::create(["career_id"=>12,"name"=>"PROBABILIDAD E INFERENCIA ESTADISTICA","creditos"=>10]);
        Subject::create(["career_id"=>12,"name"=>"PROGRAMACION I","creditos"=>8]);
        Subject::create(["career_id"=>12,"name"=>"MATEMATICAS APLICADAS","creditos"=>6]);
        Subject::create(["career_id"=>12,"name"=>"ELECTRONICA I","creditos"=>12]);
        Subject::create(["career_id"=>12,"name"=>"MECANICA DE MATERIALES II","creditos"=>6]);
        Subject::create(["career_id"=>12,"name"=>"DIBUJO ASISTIDO POR COMPUTADORA","creditos"=>3]);
        Subject::create(["career_id"=>12,"name"=>"INGLES 3","creditos"=>0]);
        Subject::create(["career_id"=>12,"name"=>"ANALISIS NUMERICO","creditos"=>6]);
        Subject::create(["career_id"=>12,"name"=>"DISEÑO DE SISTEMAS DIGITALES","creditos"=>7]);
        Subject::create(["career_id"=>12,"name"=>"ELECTRONICA II","creditos"=>8]);
        Subject::create(["career_id"=>12,"name"=>"CIRCUITOS Y MOTORES ELECTRICOS","creditos"=>8]);
        Subject::create(["career_id"=>12,"name"=>"MODELADO Y SIMULACION DE SISTEMAS","creditos"=>7]);
        Subject::create(["career_id"=>12,"name"=>"CINEMATICA DE LAS MAQUINAS","creditos"=>10]);
        Subject::create(["career_id"=>12,"name"=>"INGLES 4","creditos"=>0]);
        Subject::create(["career_id"=>12,"name"=>"PRINCIPIOS DE ADMINISTRACION","creditos"=>6]);
        Subject::create(["career_id"=>12,"name"=>"INSTRUMENTACION INDUSTRIAL","creditos"=>7]);
        Subject::create(["career_id"=>12,"name"=>"MICROCONTROLADORES","creditos"=>7]);
        Subject::create(["career_id"=>12,"name"=>"ELECTRONICA INDUSTRIAL A","creditos"=>8]);
        Subject::create(["career_id"=>12,"name"=>"INGENIERIA DE CONTROL I","creditos"=>8]);
        Subject::create(["career_id"=>12,"name"=>"DISEÑO MECANICO A","creditos"=>11]);
        Subject::create(["career_id"=>12,"name"=>"INGLES 5","creditos"=>0]);
        Subject::create(["career_id"=>12,"name"=>"CONTROL DE CALIDAD","creditos"=>6]);
        Subject::create(["career_id"=>12,"name"=>"PROGRAMACION II","creditos"=>8]);
        Subject::create(["career_id"=>12,"name"=>"ELECTRONEUMATICA","creditos"=>8]);
        Subject::create(["career_id"=>12,"name"=>"INGENIERIA DE CONTROL II","creditos"=>8]);
        Subject::create(["career_id"=>12,"name"=>"ROBOTICA A","creditos"=>10]);
        Subject::create(["career_id"=>12,"name"=>"PROCESOS DE MANUFACTURA I","creditos"=>10]);
        Subject::create(["career_id"=>12,"name"=>"LIDERAZGO Y EMPRENDIMIENTO","creditos"=>3]);
        Subject::create(["career_id"=>12,"name"=>"VALIDACION DE LA LENGUA EXTRANJERA","creditos"=>0]);
        Subject::create(["career_id"=>12,"name"=>"INVESTIGACION DE OPERACIONES I","creditos"=>6]);
        Subject::create(["career_id"=>12,"name"=>"CONTROL LOGICO PROGRAMABLE","creditos"=>8]);
        Subject::create(["career_id"=>12,"name"=>"INTERFACES HW-SW","creditos"=>8]);
        Subject::create(["career_id"=>12,"name"=>"ADMINISTRACION DE PROYECTOS","creditos"=>6]);
        Subject::create(["career_id"=>12,"name"=>"INGENIERIA Y GESTION AMBIENTAL","creditos"=>3]);
        Subject::create(["career_id"=>12,"name"=>"PROCESOS DE MANUFACTURA II","creditos"=>8]);
        Subject::create(["career_id"=>12,"name"=>"REDES INDUSTRIALES","creditos"=>12]);
        Subject::create(["career_id"=>12,"name"=>"PROYECTO INTEGRADOR IMT","creditos"=>10]);
        Subject::create(["career_id"=>12,"name"=>"SEMINARIO","creditos"=>2]);
        Subject::create(["career_id"=>12,"name"=>"PRACTICAS PROFESIONALES I","creditos"=>15]);
        Subject::create(["career_id"=>12,"name"=>"SEMINARIO DE EGRESO","creditos"=>0]);
        Subject::create(["career_id"=>13,"name"=>"GEOMETRIA Y TRIGONOMETRIA","creditos"=>0]);
        Subject::create(["career_id"=>13,"name"=>"ALGEBRA A","creditos"=>8]);
        Subject::create(["career_id"=>13,"name"=>"SEMINARIO DE ORIENTACION","creditos"=>0]);
        Subject::create(["career_id"=>13,"name"=>"INTRODUCCION A LOS MATERIALES","creditos"=>10]);
        Subject::create(["career_id"=>13,"name"=>"ORIGEN DE LOS MATERIALES","creditos"=>10]);
        Subject::create(["career_id"=>13,"name"=>"QUIMICA A","creditos"=>8]);
        Subject::create(["career_id"=>13,"name"=>"METODOLOGIA DE LA INVESTIGACION","creditos"=>4]);
        Subject::create(["career_id"=>13,"name"=>"TECNICAS DE COMUNICACION ORAL Y ESCRITA","creditos"=>5]);
        Subject::create(["career_id"=>13,"name"=>"FISICA A","creditos"=>8]);
        Subject::create(["career_id"=>13,"name"=>"ALGEBRA B","creditos"=>8]);
        Subject::create(["career_id"=>13,"name"=>"CALCULO A","creditos"=>8]);
        Subject::create(["career_id"=>13,"name"=>"DINAMISMO I","creditos"=>6]);
        Subject::create(["career_id"=>13,"name"=>"MINERALOGIA","creditos"=>10]);
        Subject::create(["career_id"=>13,"name"=>"QUIMICA DE MATERIALES","creditos"=>10]);
        Subject::create(["career_id"=>13,"name"=>"FISICA C","creditos"=>6]);
        Subject::create(["career_id"=>13,"name"=>"CALCULO B","creditos"=>8]);
        Subject::create(["career_id"=>13,"name"=>"DINAMISMO II","creditos"=>6]);
        Subject::create(["career_id"=>13,"name"=>"OBTENCION DE MATERIALES","creditos"=>10]);
        Subject::create(["career_id"=>13,"name"=>"ANALISIS DE MATERIALES","creditos"=>10]);
        Subject::create(["career_id"=>13,"name"=>"ARTE- CULTURA Y HUMANIDADES I","creditos"=>2]);
        Subject::create(["career_id"=>13,"name"=>"TENDENCIAS SOCIALES","creditos"=>2]);
        Subject::create(["career_id"=>13,"name"=>"INGLES 1","creditos"=>0]);
        Subject::create(["career_id"=>13,"name"=>"INGENIERIA ELECTRICA","creditos"=>6]);
        Subject::create(["career_id"=>13,"name"=>"CALCULO E","creditos"=>8]);
        Subject::create(["career_id"=>13,"name"=>"MECANICA DE FLUIDOS","creditos"=>8]);
        Subject::create(["career_id"=>13,"name"=>"PRINCIPIOS DE ECONOMIA","creditos"=>10]);
        Subject::create(["career_id"=>13,"name"=>"MATERIALES DE INGENIERIA I","creditos"=>12]);
        Subject::create(["career_id"=>13,"name"=>"GESTION Y DESARROLLO SOCIAL","creditos"=>2]);
        Subject::create(["career_id"=>13,"name"=>"INGLES 2","creditos"=>0]);
        Subject::create(["career_id"=>13,"name"=>"INSTRUMENTACION","creditos"=>5]);
        Subject::create(["career_id"=>13,"name"=>"ECOLOGIA I","creditos"=>6]);
        Subject::create(["career_id"=>13,"name"=>"COMPUTACION APLICADA","creditos"=>4]);
        Subject::create(["career_id"=>13,"name"=>"FISICOQUIMICA","creditos"=>10]);
        Subject::create(["career_id"=>13,"name"=>"BENEFICIO DE MATERIALES I","creditos"=>12]);
        Subject::create(["career_id"=>13,"name"=>"MATERIALES DE INGENIERIA II","creditos"=>8]);
        Subject::create(["career_id"=>13,"name"=>"ACTIVIDADES ARTISTICAS- DEPORTIVAS O DE DIVULGACION","creditos"=>2]);
        Subject::create(["career_id"=>13,"name"=>"INGLES 3","creditos"=>0]);
        Subject::create(["career_id"=>13,"name"=>"PRACTICAS PROFESIONALES I","creditos"=>15]);
        Subject::create(["career_id"=>13,"name"=>"MATEMATICAS APLICADAS","creditos"=>6]);
        Subject::create(["career_id"=>13,"name"=>"TERMODINAMICA DE MATERIALES","creditos"=>10]);
        Subject::create(["career_id"=>13,"name"=>"BENEFICIO DE MATERIALES II","creditos"=>12]);
        Subject::create(["career_id"=>13,"name"=>"MECANICA DE MATERIALES","creditos"=>10]);
        Subject::create(["career_id"=>13,"name"=>"CERAMICOS","creditos"=>6]);
        Subject::create(["career_id"=>13,"name"=>"GESTION DE PROYECTOS","creditos"=>3]);
        Subject::create(["career_id"=>13,"name"=>"INGLES 4","creditos"=>0]);
        Subject::create(["career_id"=>13,"name"=>"ADMINISTRACION","creditos"=>6]);
        Subject::create(["career_id"=>13,"name"=>"FENOMENOS DE TRANSPORTE","creditos"=>10]);
        Subject::create(["career_id"=>13,"name"=>"EXTRACTIVA I","creditos"=>12]);
        Subject::create(["career_id"=>13,"name"=>"FORMADO DE MATERIALES","creditos"=>10]);
        Subject::create(["career_id"=>13,"name"=>"POLIMEROS","creditos"=>6]);
        Subject::create(["career_id"=>13,"name"=>"INGLES 5","creditos"=>0]);
        Subject::create(["career_id"=>13,"name"=>"CONTROL DE CALIDAD","creditos"=>6]);
        Subject::create(["career_id"=>13,"name"=>"FUNDICION","creditos"=>8]);
        Subject::create(["career_id"=>13,"name"=>"CINETICA","creditos"=>8]);
        Subject::create(["career_id"=>13,"name"=>"EXTRACTIVA II","creditos"=>12]);
        Subject::create(["career_id"=>13,"name"=>"TRANSFORMACIONES DE FASES","creditos"=>10]);
        Subject::create(["career_id"=>13,"name"=>"LIDERAZGO Y EMPRENDIMIENTO","creditos"=>3]);
        Subject::create(["career_id"=>13,"name"=>"ECOLOGIA II","creditos"=>8]);
        Subject::create(["career_id"=>13,"name"=>"SIMULACION","creditos"=>8]);
        Subject::create(["career_id"=>13,"name"=>"SELECCION Y USO DE MATERIALES","creditos"=>8]);
        Subject::create(["career_id"=>13,"name"=>"DISEÑO DE PROCESOS","creditos"=>10]);
        Subject::create(["career_id"=>14,"name"=>"HERRAMIENTAS DE SOFTWARE","creditos"=>8]);
        Subject::create(["career_id"=>14,"name"=>"PENSAMIENTO ALGORITMICO","creditos"=>8]);
        Subject::create(["career_id"=>14,"name"=>"MATEMATICAS DISCRETAS I","creditos"=>8]);
        Subject::create(["career_id"=>14,"name"=>"TEMAS SELECTOS DE MATEMATICAS","creditos"=>8]);
        Subject::create(["career_id"=>14,"name"=>"QUIMICA A","creditos"=>8]);
        Subject::create(["career_id"=>14,"name"=>"METODOLOGIA DE LA INVESTIGACION","creditos"=>4]);
        Subject::create(["career_id"=>14,"name"=>"SEMINARIO DE ORIENTACION EN COMPUTACION","creditos"=>2]);
        Subject::create(["career_id"=>14,"name"=>"SISTEMAS INTERACTIVOS","creditos"=>8]);
        Subject::create(["career_id"=>14,"name"=>"ESTRUCTURAS DE DATOS I","creditos"=>8]);
        Subject::create(["career_id"=>14,"name"=>"MATEMATICAS DISCRETAS II","creditos"=>8]);
        Subject::create(["career_id"=>14,"name"=>"ALGEBRA B","creditos"=>8]);
        Subject::create(["career_id"=>14,"name"=>"CALCULO A","creditos"=>8]);
        Subject::create(["career_id"=>14,"name"=>"TENDENCIAS SOCIALES","creditos"=>2]);
        Subject::create(["career_id"=>14,"name"=>"INGLES 1","creditos"=>5]);
        Subject::create(["career_id"=>14,"name"=>"INGENIERIA DE SOFTWARE","creditos"=>8]);
        Subject::create(["career_id"=>14,"name"=>"ESTRUCTURAS DE DATOS II","creditos"=>8]);
        Subject::create(["career_id"=>14,"name"=>"LENGUAJES DE PROGRAMACION","creditos"=>8]);
        Subject::create(["career_id"=>14,"name"=>"FISICA A","creditos"=>8]);
        Subject::create(["career_id"=>14,"name"=>"CALCULO B","creditos"=>8]);
        Subject::create(["career_id"=>14,"name"=>"ARQUITECTURA DE COMPUTADORAS","creditos"=>8]);
        Subject::create(["career_id"=>14,"name"=>"INGLES 2","creditos"=>5]);
        Subject::create(["career_id"=>14,"name"=>"BASES DE DATOS","creditos"=>8]);
        Subject::create(["career_id"=>14,"name"=>"TECNOLOGIA ORIENTADA A OBJETOS","creditos"=>8]);
        Subject::create(["career_id"=>14,"name"=>"ALGORITMOS Y COMPLEJIDAD","creditos"=>8]);
        Subject::create(["career_id"=>14,"name"=>"ANALISIS NUMERICO","creditos"=>8]);
        Subject::create(["career_id"=>14,"name"=>"CALCULO D","creditos"=>8]);
        Subject::create(["career_id"=>14,"name"=>"SOFTWARE DE SISTEMAS","creditos"=>8]);
        Subject::create(["career_id"=>14,"name"=>"GRAFICACION POR COMPUTADORA","creditos"=>8]);
        Subject::create(["career_id"=>14,"name"=>"INTERFACES GRAFICAS CON APLICACIONES","creditos"=>8]);
        Subject::create(["career_id"=>14,"name"=>"FUNDAMENTOS DE INTELIGENCIA ARTIFICIAL","creditos"=>8]);
        Subject::create(["career_id"=>14,"name"=>"SISTEMAS OPERATIVOS","creditos"=>8]);
        Subject::create(["career_id"=>14,"name"=>"REDES DE COMPUTADORAS Y SEGURIDAD","creditos"=>8]);
        Subject::create(["career_id"=>14,"name"=>"GESTION Y DESARROLLO SOCIAL","creditos"=>2]);
        Subject::create(["career_id"=>14,"name"=>"INGLES 3","creditos"=>5]);
        Subject::create(["career_id"=>14,"name"=>"TECNICAS DE COMUNICACION ORAL Y ESCRITA","creditos"=>5]);
        Subject::create(["career_id"=>14,"name"=>"ADMINISTRACION DE PROYECTOS I","creditos"=>8]);
        Subject::create(["career_id"=>14,"name"=>"ELECTIVA DE �REA DE �NFASIS I","creditos"=>8]);
        Subject::create(["career_id"=>14,"name"=>"ELECTIVA DE �REA DE �NFASIS II","creditos"=>8]);
        Subject::create(["career_id"=>14,"name"=>"PROBABILIDAD Y ESTADISTICA","creditos"=>8]);
        Subject::create(["career_id"=>14,"name"=>"ARTE- CULTURA Y HUMANIDADES I","creditos"=>2]);
        Subject::create(["career_id"=>14,"name"=>"INGLES 4","creditos"=>5]);
        Subject::create(["career_id"=>14,"name"=>"PROYECTOS COMPUTACIONALES I","creditos"=>8]);
        Subject::create(["career_id"=>14,"name"=>"ADMINISTRACION DE PROYECTOS II","creditos"=>8]);
        Subject::create(["career_id"=>14,"name"=>"ELECTIVA DE �REA DE �NFASIS III","creditos"=>8]);
        Subject::create(["career_id"=>14,"name"=>"ELECTIVA DE �REA DE �NFASIS IV","creditos"=>8]);
        Subject::create(["career_id"=>14,"name"=>"MODELADO MATEMATICO","creditos"=>8]);
        Subject::create(["career_id"=>14,"name"=>"LIDERAZGO Y EMPRENDIMIENTO","creditos"=>3]);
        Subject::create(["career_id"=>14,"name"=>"INGLES 5","creditos"=>5]);
        Subject::create(["career_id"=>14,"name"=>"PROYECTOS COMPUTACIONALES II","creditos"=>8]);
        Subject::create(["career_id"=>14,"name"=>"ELECTIVA DE �REA DE �NFASIS V","creditos"=>8]);
        Subject::create(["career_id"=>14,"name"=>"ELECTIVA DE �REA DE �NFASIS VI","creditos"=>8]);
        Subject::create(["career_id"=>14,"name"=>"ELECTIVA DE �REA DE �NFASIS VII","creditos"=>8]);
        Subject::create(["career_id"=>14,"name"=>"ELECTIVA DE �REA DE �NFASIS VIII","creditos"=>8]);
        Subject::create(["career_id"=>14,"name"=>"ARTE- CULTURA Y HUMANIDADES II","creditos"=>2]);
        Subject::create(["career_id"=>14,"name"=>"ACTIVIDADES DE APRENDIZAJE I","creditos"=>2]);
        Subject::create(["career_id"=>14,"name"=>"PROYECTOS COMPUTACIONALES III","creditos"=>8]);
        Subject::create(["career_id"=>14,"name"=>"INVESTIGACI�N EN COMPUTACI�N","creditos"=>8]);
        Subject::create(["career_id"=>14,"name"=>"SEMINARIO DE EGRESO ISI","creditos"=>1]);
        Subject::create(["career_id"=>14,"name"=>"MOVILIDAD I","creditos"=>6]);
        Subject::create(["career_id"=>14,"name"=>"SEMINARIO DE EGRESO EGRESO","creditos"=>0]);
        Subject::create(["career_id"=>14,"name"=>"ACTIVIDADES ARTISTICAS- DEPORTIVAS O DE DIVULGACION","creditos"=>2]);
        Subject::create(["career_id"=>14,"name"=>"PRACTICAS PROFESIONALES I","creditos"=>15]);
        Subject::create(["career_id"=>15,"name"=>"HERRAMIENTAS DE COMPUTO","creditos"=>8]);
        Subject::create(["career_id"=>15,"name"=>"DIBUJO PARA INGENIEROS","creditos"=>5]);
        Subject::create(["career_id"=>15,"name"=>"INTRODUCCION A LA TOPOGRAFIA Y CONSTRUCCION","creditos"=>8]);
        Subject::create(["career_id"=>15,"name"=>"GEOMETRIA Y TRIGONOMETRIA","creditos"=>0]);
        Subject::create(["career_id"=>15,"name"=>"GEOLOGIA","creditos"=>8]);
        Subject::create(["career_id"=>15,"name"=>"ALGEBRA A","creditos"=>8]);
        Subject::create(["career_id"=>15,"name"=>"GEOMETRIA DESCRIPTIVA","creditos"=>5]);
        Subject::create(["career_id"=>15,"name"=>"METODOLOGIA DE LA INVESTIGACION","creditos"=>4]);
        Subject::create(["career_id"=>15,"name"=>"TRIGONOMETRIA PLANA Y DEL ESPACIO","creditos"=>5]);
        Subject::create(["career_id"=>15,"name"=>"TOPOGRAFIA PLANIMETRICA","creditos"=>10]);
        Subject::create(["career_id"=>15,"name"=>"QUIMICA A","creditos"=>8]);
        Subject::create(["career_id"=>15,"name"=>"FISICA A","creditos"=>8]);
        Subject::create(["career_id"=>15,"name"=>"MATERIALES DE CONSTRUCCION","creditos"=>7]);
        Subject::create(["career_id"=>15,"name"=>"ALGEBRA B","creditos"=>8]);
        Subject::create(["career_id"=>15,"name"=>"TENDENCIAS SOCIALES","creditos"=>2]);
        Subject::create(["career_id"=>15,"name"=>"TECNICAS DE COMUNICACION ORAL Y ESCRITA","creditos"=>5]);
        Subject::create(["career_id"=>15,"name"=>"ASTRONOMIA PARA EL POSICIONAMIENTO","creditos"=>5]);
        Subject::create(["career_id"=>15,"name"=>"TOPOGRAFIA ALTIMETRICA","creditos"=>10]);
        Subject::create(["career_id"=>15,"name"=>"PROYECCIONES CARTOGRAFICAS","creditos"=>8]);
        Subject::create(["career_id"=>15,"name"=>"CONSTRUCCION I","creditos"=>10]);
        Subject::create(["career_id"=>15,"name"=>"CALCULO A","creditos"=>8]);
        Subject::create(["career_id"=>15,"name"=>"GESTION Y DESARROLLO SOCIAL","creditos"=>2]);
        Subject::create(["career_id"=>15,"name"=>"TALLER DE HABILIDADES DIGITALES","creditos"=>3]);
        Subject::create(["career_id"=>15,"name"=>"INGLES 1","creditos"=>0]);
        Subject::create(["career_id"=>15,"name"=>"GEODESIA","creditos"=>8]);
        Subject::create(["career_id"=>15,"name"=>"TOPOGRAFIA EN VIAS TERRESTRES","creditos"=>8]);
        Subject::create(["career_id"=>15,"name"=>"TOPOGRAFIA SUBTERRANEA","creditos"=>8]);
        Subject::create(["career_id"=>15,"name"=>"GENERACION DE CARTOGRAFIA","creditos"=>8]);
        Subject::create(["career_id"=>15,"name"=>"CONSTRUCCION II","creditos"=>10]);
        Subject::create(["career_id"=>15,"name"=>"ADMINISTRACION DE EMPRESAS","creditos"=>8]);
        Subject::create(["career_id"=>15,"name"=>"LIDERAZGO Y EMPRENDIMIENTO","creditos"=>3]);
        Subject::create(["career_id"=>15,"name"=>"INGLES 2","creditos"=>0]);
        Subject::create(["career_id"=>15,"name"=>"SISTEMAS DE POSICIONAMIENTO","creditos"=>8]);
        Subject::create(["career_id"=>15,"name"=>"INGENIERIA DE TRANSITO","creditos"=>8]);
        Subject::create(["career_id"=>15,"name"=>"GEOTECNIA I","creditos"=>12]);
        Subject::create(["career_id"=>15,"name"=>"CONSTRUCCION III","creditos"=>10]);
        Subject::create(["career_id"=>15,"name"=>"GERENCIA DE PROYECTOS","creditos"=>6]);
        Subject::create(["career_id"=>15,"name"=>"INGLES 3","creditos"=>0]);
        Subject::create(["career_id"=>15,"name"=>"TOPOGRAFIA EN OBRA CIVIL","creditos"=>10]);
        Subject::create(["career_id"=>15,"name"=>"HIDROSISTEMAS","creditos"=>8]);
        Subject::create(["career_id"=>15,"name"=>"PROYECTO INTEGRADOR","creditos"=>6]);
        Subject::create(["career_id"=>15,"name"=>"LICITACION DE OBRAS","creditos"=>6]);
        Subject::create(["career_id"=>15,"name"=>"MODELADO EN OBRAS HIDRAULICAS","creditos"=>8]);
        Subject::create(["career_id"=>15,"name"=>"CONSTRUCCION IV","creditos"=>6]);
        Subject::create(["career_id"=>15,"name"=>"ACTIVIDADES ARTISTICAS- DEPORTIVAS O DE DIVULGACION","creditos"=>2]);
        Subject::create(["career_id"=>15,"name"=>"ARTE- CULTURA Y HUMANIDADES I","creditos"=>2]);
        Subject::create(["career_id"=>15,"name"=>"INGLES 4","creditos"=>0]);
        Subject::create(["career_id"=>15,"name"=>"PRACTICAS PROFESIONALES I","creditos"=>15]);
        Subject::create(["career_id"=>15,"name"=>"INGENIERIA DE COSTOS- CONTABILIDAD Y ESTADOS FINANCIEROS","creditos"=>6]);
        Subject::create(["career_id"=>15,"name"=>"INTERPRETACION DE CARTA TEMATICA","creditos"=>6]);
        Subject::create(["career_id"=>15,"name"=>"FOTOGRAMETRIA DIGITAL","creditos"=>8]);
        Subject::create(["career_id"=>15,"name"=>"RESIDENCIA DE OBRA","creditos"=>8]);
        Subject::create(["career_id"=>15,"name"=>"MODELACION TOPOGRAFICA EN 3D","creditos"=>5]);
        Subject::create(["career_id"=>15,"name"=>"ARTE- CULTURA Y HUMANIDADES II","creditos"=>2]);
        Subject::create(["career_id"=>15,"name"=>"INGLES 5","creditos"=>0]);
    }
}
